apiVersion: v2
name: datalab
version: 1.0.0
dependencies:
  - name: mlflow
    version: 1.2.0
    repository: https://community-charts.github.io/helm-charts
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
  - name: mariadb
    version: 20.5.9
    repository: oci://registry-1.docker.io/bitnamicharts
