{{- range $name, $pvc := .Values.persistence }}
{{- if $pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "localai.fullname" $ }}-{{ $name }}
  labels:
    {{- include "localai.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $pvc.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ $pvc.storageClass }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
{{- end }}
