---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: brain-git-deploy-key
  namespace: brain
spec:
  encryptedData:
    ssh-privatekey: AgCdX3FGyv2zqMQ2jD7xDfZ/IAl/+RAS9r7Z5wGPtsUxsU2FEzL8nYPoREh436FJ71AV8U2Hb2g0ElbuGeR7VSwFf3CZKYv1qFzU4ySUIUucaANPpqGgnjLKVuU+Dx4aPO8YVXCR0vLcFfrpzzI8Tdyco3iKqVGZc6mX661VfTQVctSn/+rz70Cby9ekayqZlaP9PAY8yT8MQ6F+p2dTxWUtcaqwxCGTKJ5o8jUgurFr1jUK2giQ/yjMv0F8BU4RP6whyfGjSXo9khE2BimJNiGVu2OjVg4nyOxHpqccJUUW4GS1R9sQjo8t4OeUVwKDvOQjKRkrzuSh+OhJRm70TJeG7fFc7zl9ND9afzFZAsKdN4jH7pqNNK3RqXcgKU3tH8bR56c7JcexX+t2OOl2V1ZU9E5ixvZXy5Q5Wu9on2VX2tckR5ARuF/Mw3YdmSCNo6cVY7EXlqEswuzwy9uwnzVy+55i31Z/B9nAy9w84decOKI0MrAUtK3XID83HZRoc/u04nBKhF9ZMj+xP6Jb9E4W66dR/8JstIJYDhRcKXwaFa2FD66f8iLypidYNofyfaWTMjG2DGOQMFowywRkzrwsZg8zzFcmHlMbRXc/BNu7NSthNSBaZubMujJDxwQCv2TGl9GXE9IJBQqOq8JeKTmkbSjDpW22/4HbDjCVu+/IaSvOUa26qRHLdLCMI6DEXthCeuNGMDzOS7kflu2Xs1pkr16g3zSxenFvkTVqHo5X17ZBlljbxHqmRBhpPbL0GSGkz8xadaBFDZ6g7iqdW06dq2HyKHG/OMctQNhKQJEWjBnCBuCSF+chtrlugo0OND1GHcYfN1FlY9vtsr1F9KUy3QUxbSGevnykAPI/zlNa8hbkeuJzFeQ0o5Uh440nQ0wp93onXGAzXdFxmUF6mQUXMyQWSBmi2jWravdNo6ZCpPr6nx0zXEivqah7LcQOSY/pbiS5oR7pn/5/ZtdugNpEQYWFWrm/NeQh4Lw+UDoG46NQ5xYkEkisYYQh83yl+J1WnmzeoaCawJjwUhaSdXd9al+f4WMkRSF0PsSJpcK7lnYvmJIkx/6BIXp1yfVKad5FA430KCCuL0MKKGc79XTPKiTGhFVvkaNuQ6oBrL/qRqCoJ7MbO4Yv90K1UgWP9+S+kRtZ86kZsyht0csK9GyA5xEf3hS4WZLIZE1Nx83i3fCvU9Kbp/ILFbRpcrRgDEt32wb8+K9/RYF+UmIGnFLRC4HKgN+YkMEHnFlyjPJZu4JA+g==
  template:
    metadata:
      creationTimestamp: null
      name: brain-git-deploy-key
      namespace: brain
