---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: configarr-env
  namespace: selfhost
spec:
  encryptedData:
    RADARR_API_KEY: AgCjcF5ucqTQn7CFcJvoC18RSaKzMK+bL5XWO66TL432TuuQg/DXs2IeQpH5dixlmiN9Gq8smA0qLYhHqmSvntTJC1t+rfnkRstCkHyeYHeFHxmEVkANrYAeiUdVZjoHFzA05FxBSy6dVtFjPfEDZ7Nn0CL5YhfmLsRfLAIwjgPwvhJTV9tuPpWMo9JiQJOvfUFEBLUiMRKFmBMEpMYOedB6J0LqblhDUIrQZb5foskyMf57e9RlbTfNhfXVp3dkgagLw63Ju+kMc7OPMh5ld4M6E6nzPTMFdw0EQVSFrPKmCp6wXGCqscbpm08TK8pxDx1CnKFsD6XzPYM9BliiAkH5hD/YkngaRqtt4G+h9dNVATnuxgK0WqiFsyrUfesY/sLbs7opRxVUeay9MPwJMby2snNRYmGMA9egfXzMwpn900uXy5WdqY0TmHN4oMhaIfwugmMLQ5pbUCTf4Zr/b7URmRJkUoTW1DOl7lk3I0VhUVNFAd273gMr3kCstR1B9wIwRxSVPbUq9CphZTfBmi7bHucCqi3VwSXIJJ5mof/0tOg2jTu+FO/Z4xYQ+K1vh81VLtyrUdXpeV19Dascz9iK1kNZH/tJNsLN8y4n01EKfDPcEJ+nlezGpEnAh0bITPCyG5yAaEmV45fpI0+fviMFaLGuQ7+4c2RvfJHg/tH9gr/oOe3Z1vaD+Xt2SQO9dAG60dgZxfccJO1+tF3j5tVU3N47ofiRhnmKjWV6nmmnQA==
    SONARR_API_KEY: AgCDBxMtI5sRweHwgwRF2DakLB1YzuqdMnjkHwqYEda6a+t+cvTte0EWYX+ddXI1TJk1t1uqloXrr5REj9XiO3XP+nwFvMHuoK0rcWA9M2+ntGiv3uRy+Ueu5tJfzQv7T/zCDNFsabM/dqugUGAdtKdnerVv3MVFGR1aOFOXxwdmMhNP5aTov48y0ThdhqxpaZzE4wZv6mwtrtT2N2kigvKAaecb63Efw3CZbqfC2CHjuI6oIo0rAhaxYXxIvem6JzyHti2+DEe7Ge9BrKiYFDpBZJuctp5txq+MzJa83qJINApMy1AeZQvkdTJrcg0DWXZESyHGnFY+2ZX3iwZz+vDWtQB4IJynNIlJJOd453VuuWCtQhNO9IzIIlO5ZbqnB8iW7XPfltsxy50PI2GL2HANoNVVzFodtb70UvYEkWrcza0r3DCf8Cqpm/yYZIAKFOeDXH+l0u+/AGl50tYL5SLweV82I3eSU58PXhgX6BjRsaVYAgAqre1P3blIO+jRtm9CQHS5WLJ5sS+44HtTOoml4F2P7VTn2Gi/o19uynLNhPimtWSoHvKlknQwqz23000fjJsthagOvJUZzw496OA4Xu+JdeJcu/N61w27uEToaFqS0OTMP14KeaDNBHpR+dzvxdYLKGIQBV4cg2wW8DO7h97dFroqHPNTYu3PSfoFiQxLCI+pM140ELXNZAYtnlD9gpHTHR7oh7ikKZiCslUcQYRn83j2zayUnfVkKHfziA==
  template:
    metadata:
      creationTimestamp: null
      name: configarr-env
      namespace: selfhost
    type: Opaque
