---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crowdsec-lapi-secrets-ext
  namespace: crowdsec
spec:
  encryptedData:
    csLapiSecret: AgCofzrHv5HJetNI+zuHkmHP9lGxYYVEV/U3x1EBRpuPWaG8T2VKEjcsEmzgoYwRXXJuPKW0CP34RrfODSx7uwYzdaCmFIoACBg3HHhyixUWkryLpicTwtoj6L1t5zJzXusQshEJE9uh1xh/Xy3ZFGYrn3lTcdP9NriznwTEZ4LbiQH+hhYD+id6G35xDSJgGIt9ntnZBJst8vhOLMzHGZsxvn76vCfRNMDjjh3SCX96wFNUkrUOkU37Ddo83iOgwgn/Kq6KWLcIpqSp05xmHyHdK9VFr4ovmzw5jEKHCs3hxvnU96l6TFJx4jMGGnpCfbxJO0+lP3r6Z6JZX05IkPIiy9I1YhwbQ5B4Bgkvxc2wfp531MWt4YhmObCmLG/XDJ4HfWarXCLJCKyxZis9mjDHOmjypRmDXm6y2Wm+e48+sgqb6GuyLgBjcAU7OOO+U4zczXVQ/dgDSsxe2kaPqjJDTmLxmpHosO+OEMnymimBii29KMauaK+zh7Po0RO7OVQ/6k4aqrIvj120hJutpHMODI3PMkIA8UmrXWv8YCgyk2z3tAgWH4R/sBvU3MwIN/lq0sckQccMSslnhapq4IM9oOAjS8z7mTGdgEuApc5FHTQsKFyP2+cqtiUwtQ3tWgxFiThXiJVbUNZuT8vQkj4FEISd21wZcFr7QwtCXzNQyE5uB1cZ/RwyKBHHWErscYbEoGalrHjO4heGUSWblSysSXqTpz5JBU9Ogf6zpm+Pcpn5El6yWrl6EDDlKaxlP4Si/NGdR9uHrFNymJq4ii05
    registrationToken: AgDaumScAzjOK/Bembw/E6o+fOZdG6Vmqj+nuPsVt29hvWBm63R/82xU4dkg+h+EGniJnzzdFBaSESReRU4K2q3KJ/Y4fD0HBtcSPuvsDLSZmAO+5D6dZaSh53B5wqij38EJIPd2TPc0rIhoeXc6w9Pv+cHFi9sG1WDjqCkiXrMrPM+ho5nSRTWsflGktdSk6tM/x3LZEg768jYZwvSOZ/WP45mpE23VNUBNAO4HFVVTVUZFWIbucst8ovCHpbDFUyp7VpuQDYhC9KqxOBpP0tHx7ucN3ePPo45DtXAGYvp5AEuwqHv9lw6N9KW3Xse0aVd8qUSWpHXzB6WgYgZJdqP7MNT4XenH1oVX7oN/Tbi1htQvLkYdFkri50AJpeKyjNjCaiLNKHEMfObv8FW0GHDliafuaDIoAB5YKAfEaTyStjyqPovBxcPDZmteEYyblDFE7cFKwcjuomlzrcaXu9Bfb9wVV5n38pT4trT8KGM86BpyNnZ2RKWUxyIO+xow2uwqsiQvQaN0MrtrjSGbpJGXZur3zAJIFeW7EHlArEmdxfXNNKX66YcvC3U3T4L7Qt7/FsCNanJbXyScwMM/8arzMb6OcklJKuqQbCrcmDeQuvHgaf2w7zivYjSaZFe9/K1fLPKTYhZRacgX22E4Y3BwmbsSDA7Mmy0yqDq062NJLRM8xXD4hZRB8ubFPkXizF+vOhkEMdziNG5Jt3IVINaGzEO4bZwfDsAVKj/C5ThkmoLb4nZjuJ+K/1ypIwNvN8g=
  template:
    metadata:
      creationTimestamp: null
      name: crowdsec-lapi-secrets-ext
      namespace: crowdsec
