---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openrouter-api-key
  namespace: cv
spec:
  encryptedData:
    api-key: AgAJSGsVEydALK3rTr5FeZUMBAm096GY9ijblC5goIGpQ7gKKJldO07VRpKmwOi4EbSBeMRlP0dr/4SmGWmF+HQp2g79+rCgvJCVQfrt5+krTr48+//8or+7JqvpzzNAkozYossrMSEMiKFSqEQkYhG3sqScflyeK9OP+k96meHpA2dyfgH2SVANd1KLrWeNgrAcDY6CcmlgGmgor/2A94qbgUIWowRLAgSvs4bcCUW1+HADDFCaPM1HKabbXgslsDZX5gDoi4lpq73eH8dphL3DvNNmo97ETy4oN9dDo3VZyCIkdVil3nUoxeB6sEPb8QoeMcW8lslJSPvPlnGZ9d0MIcZmmj70xwt/st7QsyqNbTV1ZKbBIJeEgIDuXnZl1aC4GlWT0UDLPzWk12a2aZwY/ExfLgR0wTQUk3cusf9BqeD/xX5kCQzoyqSjL/6XTZ0InjnslDXc/AcCGPRbozzAh3CU56kbrJQBHp6Ubw/fuA687KT4/wWHLMKXJVvgPUOf0SFh+7p0ephjjhE/PUfycSHFboAyrsVjG2wtSLkuZ4A7pWD79NuFpSD/uVAncKFNoD2hgDC9XLEHYMDonGU4JHURqXKy0KPJIUHNhsh4PQEr4qwL0M6RiHjxMR7Y1NaW832LYl5sfGNcG7zN9TJhTlxG7H3YrOVbfFwoYKRdUXVNxTQIAy7dmSQy7Vr17dGSETIs0k+CwwPRVuZF6Thh6nUiM3MusT/BvRugBFT8vnjM5LrtV6zMLO2vexkZfKH29rLd9ebPXDjTXkMv0AKe/r/s8o1jRh1D
  template:
    metadata:
      creationTimestamp: null
      name: openrouter-api-key
      namespace: cv
