---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dagster-postgres-password
  namespace: dagster
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB2HBLfdSNY7+FxGj7ceZ4ZpLIiBEfGGbHARSRHNhBqXIFKemCbzK0qS1jMUIumqlYqVmx73Qtgr7EKSsMz1kl1+klf403QNbj59kYL68+4Ykks8NkTZj7kk76xO94ZHKH3VGiRw5g6w2BHJXD9QNczSCY2fEtjD3htNRiPn5lxt9S3a0XlS5jCt1J78FG7RHjrgmYxrB9mVSt+6uD5T1xUXPZrZstoAPCrw67f0gUX8vkq/twDG+flXoJluKPLUO7Vhq0NimqfXPMBgEuAZhrA2W5ZDT/YLE4tOPZU9tInm4JqGCj2ZNATRUlhoRC3JbZkUVQX6W8O02fPZsV3E0iAI6za0I8f+WNcuInjHaLJ+tUwfLVT0GaDqbeZTq87U5dnXHiLVnXjeXhcH+5s5hqKVDnANbPCoPkzfxiX2wz4e9SCAoY6QbIUORtGhQXVHdt+jCru3eCLjAm/APMnUh7azdQzNFjMs1bnACamyKr1fOFJmFfurbeKap8MRLWWiY7bAYsvteUYMhFSlB2t+WKo2f+objZ5tpsD7WJhTj9bCRQUJVwQHmyYija79tOUNxQpQW5bc72Z/PM/aJruEV8tGuiDgIR5Yx1qNpyFPu/Nx35m9t0znjVHEsidU58hqSwxuhfcPzk8ZzXP0aZa60ZaZFLS6KMV13SQU36elJYPR18YAcVAn0dJPO61ZF4tELiXlXRj
  template:
    metadata:
      creationTimestamp: null
      name: dagster-postgres-password
      namespace: dagster
