---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-workspace-secrets
  namespace: hermes
spec:
  encryptedData:
    HERMES_API_TOKEN: AgCopqs2g38F1KtDpV0niTfFcba4kaDQ8Vu5UBI3/T8OcviqTTWvQ8dSbCY7Y1qdcFIG9CAoI9y0Bv3mDo/ALsTRyE/YrcKt0LRvm8pS4FodnE034m4y1b6+h6pztvaz9fYxj0jgGl4+oVr2nn4BJlMMT7hY5aRP71yKbVet/Ft2moYPP/UD1rf5Ib5k3gxnbRDpWS5z7gTe9E/tM3oC0fQZCLHPeNkK56P/Eh/VKvYxBj9CT36r5TvLLeWzECWY0hjkgtTKQDbTa5Xn3kMBv54DDNsVsGJLBLmWY70kmAWSEfNMR+2petoCuRLi+nyp0Bnpv4pSAoa2bSpjKeSPr5Fpbika19SX5JMQoN5iUhQLv/964KGltRL7zwrJZlmB1RVJV014/MCbDDuwVLJTAXBT+fyPDTY7m5Q23RLehkgvkp0SM5EifBJNjcmXNxQuYH2VhxOxa1jnuEYZkMsgesMSQH94fTJFUkqJBt+ghZPiSkcWPq18sVLdC0P+m0TpRz4eBAP+qyz/gq+aKPv0Zcc8pmTvVOdXZmyO3vKX/GHeMneJvmYlanVcEVQThKd9f3r8ZGeRHjlIv/3RKH5X38RtP+WE0wIjdyzmSpwDTrtDeT8ghGD73Zuo9pGn7MjpZxOpkWFLBwOYOQu4D799SQvlPH0Ln96cx7rS45cG9/WAfoJKrpCM34UnznRm9gvxBsmQlWVxbEB9rAgiIr5YFQHI4ieiN9XzOw0ih/OM2r5RMsTI5z7Gj3NLEoMHfShXstqlxYUIUkaJNJ0fa1ZrCKJN
    HERMES_PASSWORD: AgAHTXr+gEKBK/KxJZhKIQ6Lv+nU8o1qTTT+ecuJoa289jS82meY8EIpVzUxiMN+Umsw0tt7oMeY5CmXpRPWXZ7SqRTUMdk80anUx2sp7xROvtdpXLIs6Gy+hUjtZ8vNdxLLlQztIa+SG9Sv/dkwFbLLj8sa4L7o7qIO7W3dtIxtMaiDjlmhtOmwYPDXtBkP6pI4qfEYt4gXKlj5+IuHYf5VXwr8UhKyzrN8MxHV1lAgQbDe6MNuz6ISBVF+Oo+yux/PkKx9DzAxUt5oCBV0+ja0ZcG3tk+T/25DXBjb4AWTxYLl3vR0IsC06bMkIaykPob7MRD4FjRLTJe0VlhJ52/LLL7fVW0Qw6n02syl6Y8Q5ME08FgQplHn3hO45NU/oALfQ9RDu55ROgELDhQ/dlSRXF9NoDVcyiDiKsfSxeXyf5h9qq/84+nHyiKpXYju39B2+uvHnJDaYVUVtbeZIcaXBg3s0w1hsrQBbqAfrcV2zPa6Yra9Ao91480tqsMC/H4ARbR07nNZm4uPkMjlvHHXHhtkV8a2IhYtiPC5W/2RpfhlWXwBXktlgb61/sb0iaALLXk7gQFQf1G4cI4a2uUosY4K1sC/NHMWPGunSxxk8NojpGsB9+q24F7UXefYifgiaxl2B4BTJCxOeVHiws7zjzUuoso0cQPInBVypYiOMgo7m3irIYjzgTxJkZ2pvX8stp2G4YwEFpp/k+AhiD/BqatzjnOWK/A=
  template:
    metadata:
      creationTimestamp: null
      name: hermes-workspace-secrets
      namespace: hermes
