---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-secrets
  namespace: hermes
spec:
  encryptedData:
    OPENAI_API_KEY: AgAEw2XrZWG7agaJXR/4YDwqVuCEj4KGnr47MH5kssAeKMY7+3Ph67en9XgrS/OtdRtXxDA9dOyCqW1JVl+hGHOPJQUtT5xWoCAHjVTSwvpH3SZhI3XaNU1mZ6lzXayrBFvEOqUHiqultm5CesFbwUNZOPCNKlSDtUTG93WDIU2A2Wx0eneHvLyED4onjsubgXDTyGUGJRPVm5EXhyY5mtLHZTCBVJvEnD5GDHwbBdfzuvoJLa0MWV2cVSYkxtbyCthNXfoX6BGLTFGICf1Ve2tCiGqUVtmqPKrCfqr4h3PII/yF+BDX0rMh31OL8EWXyeWSWlApcyo2gVElF/N8koQknrc8f1yGSinKM2EuA2zGNFQJWXfjHuP50t1u+i6V1lm4erjFbuhUvgr+6sX133kgXkWR9Wcue/tGwd8kHi5he8xDFuYsMq1rWaDs2BwMWNFCd9XMTC/jMqLRjDAeA22SJo9somBmBbAvfCjUD91MS1YleQpN/Eb/2N+lrJHv+ZaoWk5NS4y+9T7ZI+oRhIMRopjiBz4y2dkgnOyp1fTAdkbpU8sau5FuDMWxkgVdp/bIQ4Do6tsKPDU1W+YDa0qXdG11f7V3/xh5PWmIj+5yuSTAeuPjrBdxqq3aQTr+Ije59xJxJ4B6VuqB6fZjRBoxWWx1oXz4+1QX4R+ZQGQXmwzHp8GbyvUxbhl0WEZvFRhN5rxqft97AOF9WQ68mHUtKB1fmT9fBSBX1hmJIVYBSh8BvTNouTPrvYBa9g==
    TELEGRAM_BOT_TOKEN: AgAH82OaWsqGlLTkCI4RBmPcEOVYLIAVMCQfB/ns3O1hH4zmV1YqZx6UFrIvllhrQl0oLRJ5yzgWh4QFayAEr9Nm/l3jCfI9PW1TSFMsnZh1TogvNlSNF9Qy6nKEZcDUhVGvxyisAF9K13fAk0BvEzR91vS67RxIaU+iHhey9BXfIyCDjXv8dCgrqWwFenS8zzRXn9gTJV79D7gGSrj2sdQTdHFnjgMMv8nJTpx3xY6ia9XonE+weio8qa3tFi6nwWWqC1wesznajnB+6vDikxtTrx4RSCNQ9E1tPJ3z23I55ae8xbQw4NBhS1Pb/gqdMEKHGG3kb0iZE9OQPepLweozDms55L9Q+7XyW5dZzlPIdW2/3zfKjxtIm75pzJY53PpkJKI4TOv6jBvaJW7uoEZXh7HAqRCvXyhU/yAfFs6wGovzK0u15vQck1B+8AEZBDOOTDjLCHAdx8xXOoG7dNJThjUa/a9vTlO483dntaIfECpMRbdsDGFrn7DMWmJ9nvc08qftR+73HDmPe30IYOAKvqGf6VwG2OA8Hc3gvnvwgruvuigs3QbNiziK2Ka83HsoWaXcPWZW9YFPXFrblkdiD9jGNi+VZpzGGAt/GG7xHon/ch7G6Yi9dm3M74l3YkLRQtcuSaokK1tKw0BV96a2gUJbhhNPBm+/OuA65cyQ2rFb+9OsrjnKu7Y5Z86q/MVvqD8A/wNHPQYkDxwYvsT3Keyf5kauVOxfCehF4OvuSGe6qVAWF6rR1EcB7Cyl
  template:
    metadata:
      creationTimestamp: null
      name: hermes-secrets
      namespace: hermes
