---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kestra-flow-secrets
  namespace: kestra
spec:
  encryptedData:
    SECRET_LOCALAI_API_KEY: AgAgy2JYa53pj16gjyVVFh3DP8tVifOuD2prRYIOS1HFhMnjLxOmAIILRzhALJreoa3E8KXjzvGJvqr9UJSLkPioo5MKToTlcxQdEh9xWjPg+ukgCxjOsjI4nYbeSHCCOaRGlqAujP/Fd60BlBbjIkzpG3fl8mpg1Hf4cSR/+PAliLvL9iiO8DECiLrRO3/A2mDP1XNTy1pp3YRaLDlIFj4Gozj8BvlG0rRx6LS+Y6BlTv0zlflck9l40fyZ7HxJx3cmUkxVXXtYicAmQugot0ZsI6hNOGyULhFr0pfXzyNM9R2440lerTZl7TuOyTT73xj6hlju15PNWrZLP/O3NZa13o4eILIqdMWKfzB8/3empFDpdUyWFrHOVkqJdGhVVuHASPNsrDN8IIpbuntSKOlKgsKkQFL+mTfN2fjIhEHGsnG4Y6lAURRG3FQEjU3BcLwwk62e4kf8vPLZMdWvb11fkEtJ/QuTdLbiwRc3eIs3hNJeVLKuIaV8hspxIqazK8EsxK4RmH0WaEyd5tXywDkd3h+aQuJR499PaPWoNDPWSnTCj41Difj7thgQlRpxxAZfRPYTBZqZSD17V/CpBzhrZ4HM91wGjzpdIS99S8WE+XfvTCmFo3hXt5DDoRd5JTKVxd1lQjnkckCN61vnbvWXdCSroLGlUCVDjjaN8GRRy+wXmWJxg0y3qdV/jmeBzKTT2W07JEs40vOPp/rUSAJ3pYR5bKro2gGUn1JSvBNBze6hVsoRHxG3JEIOFrS20l4dTBF5row4usmvlEg=
    SECRET_TELEGRAM_TOKEN: AgBop+GFJhH3NAJML3XuzFZooeH3GDPej4QlnLFwCGR9StcMiOGA8rweYyt2ddTk58ADkFFf6t53zE43eY74l7k29ViDAoL+eQ0NDsCot5ZbzLme8tpJ6lyp4oUaGJeibDX6ng7vBZTIgtpc5U4v6JbdGZiS0e9zuw+xvneX4TsZMRWsfmVqNU1+htCmw+6O1ZMNgfQQrTXTJr/g1gIHyzay3Is4a3XZ7M4x7kwNPszXIcSWWem9fspn82GxdT1Lke1vudp2ncY9BJl7I+imWRkOfnLaDVFzOtRkajL6ySvnHN/XN6U5MmBT9DpB+kLc3IOLZWhaK9R2tdYTIC5QbRkRXEhJhu3oVNPMbk8FUygy4tNrN2O4LgacRYpIMsCMh9izbLe8PfUn9+HKwb+JEX0W5oIR3FSDrNqim202i1BcYoliY+Fa2rXEgF+IMuhpyFv3hcBp8fKordeHLZ0dnaBI+5WtmG2DMgv2kMasNCMJHG/Krt/cnDZbqZJIcZc1ZbPoUoc5qckhHTVX4OwX38HqhsMOZhe4hqeXpf7nf7+IeqKJH+zVXE12CAPGoC0EJfq0Z7FpX8OChTgydfQjJGQ80uoS63fTRAJoneV6q2BSIzExZQekoVJM0zKYQivXJdwmpMshRoKRxscaZOnk9kyUFFz6SJgqRpkzriFdS+gMnSc0cwyxAwpEmqWD5U+0cmvr/IE4MJyR5+dc6GsfZGaT7wu6tYey0dY1TjFu1lQLJJMYpIVpEY3254xX5HkBNVk5zFcLcnMVlvz7PmwagKvj
  template:
    metadata:
      creationTimestamp: null
      name: kestra-flow-secrets
      namespace: kestra
