---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: localai-api-key
  namespace: localai
spec:
  encryptedData:
    api-key: AgAEID401mszGpn8zU2lmxZ1RQAjttC//N64LZNKWsNRIXj1opXMsndpmnMOyJhy/tnteJiKLpwgDQRBc0e29Wll0CRIFUuFS9JwBIy2N+m53vD8xrkxp6of1AvQXS1hQOFNxmcvgn5ZmhfcovYXvru3jB8mVzYpWIPe9wDdBX474KAfajRAD1LFR+Slcd6dXO6NHiQnGz6kWmfvfj4C5YHi4VzJJVH+Lauwj0Nx6TmOj8VSs1mXWZ6eDu3tGsFutU9G87PPOhINz/HHQmWp24JBduLvbDNfbDVt2Wdrd9kxceO+vZ0mSd6fgtGmrJ7+A3w0SMGlLp+E5gytKwZ5kUZQ/QW6YZ38Mc5Z9QFYUwTjQW67INBCqtkXXzMQiGV715N3RTr0NHD1Qhw6auw6PoRgDwq4PFWhcpTdVrDiKe0bUKteL6LvBWlam3DQBUDJ0V/bx1tBY+BY7eAgW7UNKTbYlYlJ0veC94IAf+S40YuNptRBrrUDO5ebIZmQuO+/o0tLMX3alJy3t5y69u6GV0G3yh3XbIhWNNXeN71RJ5GRdha7qlFkpOmJAtrIKQPO0tQNPrCDzb1kgbr7B/DhyFXjroKDIrv7l4RUJqQjqkgx9buqa7CGMrL/2vqB5ZGeowgDdhXuW4aTu+sOEMWM3PTPNBA0HW1345yhKtTJf4SiYpZQF0pHhdncs+QICX494dfAFdv/VXE9SFRkJ2E5WssZGcIfEzidttS6QRoLdjldul8LKQzVVnd8V00seQ==
  template:
    metadata:
      creationTimestamp: null
      name: localai-api-key
      namespace: localai
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: localai-api-key
  namespace: openwebui
spec:
  encryptedData:
    api-key: AgCjYIdoovcMAKsFHt4QBMQx/rkuIzGuyr3PFsZHicRDfSip1kz1k8EaqrlhF/f5EW4Kf1e+WgUFYZe/LMImSlNwZhHmnspswvuTfModLvyIlAU8js0+YiF9sfJXJ+IH6+Ci+X25P+0DYGAI8MvYCXX5+vbjzyxkTyrSI9tfH9youGn48rKs7O2qfGIqHUdigmj2TUZwdzr0Q4ayBPV7SQLExr4iDUKCvX+mdhYzW+qVYFqKIh/8z9erh1YxdeQzRFChnX1cbSSp9maMBHNrXTGwoyyEHq+ZHB7r05Iw22ckR+pWVhs61GyvkuFkAnIu2j1qUsN2PPVuZTiP+eZjVSXcf8rULzCa3G7CjDXEa7QKnC1qc6t5AJbdhfmeIbOToKRYJt1YCsolWwiWsrcmkppivaqB3yopZrJ6xRbRq39N8TDx9tTNGDEt2hONnyz3bRe2WaAcWQs+lDzwcJXrAsKifwGcc9dAsqBNdTXfIJspRbfgXTAkcE5sg7wYmrvG7aqNnGmB01lyGR/G4GXLjkX3e2Nc6RzWAbCxyzJkh3nYoMSKsF4wdJUxNOKI7kopvRCXkfAHdSeH5ilYk3NZ0M8PzleWnHPQMgT32qHBRDaIUdERwLU/fwL32JrbjN/GsCgEy4VQKIacfE77EB13YuNwxdeDrymuS87ECKy0M8XGp43nF0xHoCZK70kt4LesczaCd6Pxta+d9RDj+5sfMud43aatgvAVWvFWDnUtr85ovLHLIqt+31xypAtvjQ==
  template:
    metadata:
      creationTimestamp: null
      name: localai-api-key
      namespace: openwebui
    type: Opaque
