---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: marmite-secrets
  namespace: selfhost
spec:
  encryptedData:
    SECRET_KEY: AgBkSH8iuZ0LNr8ph+41dkotRV+d9AAhjcZLE152J2vo5gEM0HOXrF8RS3jXxW8/XbL0abPYYgovP9yqFYqzch+mAhwHXJeyriB0qzZ+qVL5a2Qd9pML1vRfLQjw1nM0OOFqzdLjD13sWIP3AYSFFJUCWmWT30QUQLQR/f7he+wd5Vh6wgKVNlgwTL+hobsQfA7OUFlEFH/Ms7gD8z7xpEZ3EmeW38m6jdPWxG+YQOWpHAuEuEhBuTb2a+Sb9cRI1YAism3/u87NAgyQT7mkQmR5YCSJ5JshRhL1BDViGkVD0A64lPOZD9+HXHrth0eETkrDESLcW7vni36083PnVyxE48gYaWmu1JiBSWtIpW+d7n3nfsv11mEGa42qJQX8RYBsQvuNqhhaeMea8p3Mqpsm7NP4Q3vrX6ilD8hnrHxlUWoftJA91nRO/kzyIxktiQyyPF99xABpozNl0K+QekAcwVBI2QzXtNg9QK/WYRA/qocDhcJzeSAVHcnkhtjg1TS+NZEJoWpqfqPmQvlIGHsieO8OedxRai2CZQ0p2ZImqv2WrHQky47sfWhkUkRzJtH0rhANU2B1JrvGXkSHyHWQasa36ZnJoDU//j2V6CAk5F1iuEEIqwvSol0dNTM8YMuakD2fIi9oaxBgqBhOhn1UL8OHLecfPU+0XiQ1e+J98kIBYoBxlaILy3Zov1koEMVYx+gglW4bEHukNcWIUZCF3ZATd8TOLV+49OiGITtTEzgUlB05lnk1RGsWQh5suBcWvw==
  template:
    metadata:
      creationTimestamp: null
      name: marmite-secrets
      namespace: selfhost
