---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openrouter-api-key
  namespace: localai
spec:
  encryptedData:
    api-key: AgCwZx7PtV+MkDR7nspurHh3cu+Rt+TzroRqlGnknXOK5FB2UTzdO6fKHhePpjBweJYD/uvBD4kKwrD5E3XZrxvn3xDoXGJ6+l4fFll+WScv3fRTgRSy37BwQ9C60fc/GJAjvMgOAXJdBi+kEtkpH4rILFuARA/CeuJL+vj3/ZGFsdRTjfBPfJCJ9Cdh0N+ZFcErHxITBc6sm7vohJFCPs1wVh/0XBCW1iqkDdUwstqPpyHpA4KiRxmrz2LlgzUejxC2+8dadBNJLTgCnm5ntxTppg6ZzEmN7MhWKpk1Le60ovWD5OGvKOEIiDssbpmJzAOMUOWPVWEU2sB9KL5sWn7ViazKkxGq5xt++nr2gn58nCHXg8+qCP3U5jS4Nm1dyAcMqgMkhIqMmo2splo+PnieVhHX7mRsAcIrCXMOjLb/k+NBNd4Srv7T9Tc68CjRJUXmbHMbYELT3tpBcyTocVO6CFO00zWFNLP+p7bm9Xeeg/JFuGuoBgqyqXpAnTyNkb8KXdCt3H/wgOFKrgvxyekUlBcWeLv5jJkykOFaiJb95925pjG+dStBGhzZTWXmHGnBaDdk5QTdfmrySixgaLQ0ZHeNXRXRGQCGQZRrDnxVZce/sbCk/Nl16xanf5xP15x1h5fKwrd4lyiPs0gZR5lBMRpCbnDWtz/DbJ0iq82Lan01K2vElaBEzirdFo5V/YphvUQYmEKieVRnwJP0JHRbwMxYvAb1n4SnNZ2ZZ8L9xxuxweQKl3B4YEVagWngz49IRFJASgLIZNItsRjCZVjOyrhqj1EVlv5a
  template:
    metadata:
      creationTimestamp: null
      name: openrouter-api-key
      namespace: localai
