---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-password
  namespace: dagster
spec:
  encryptedData:
    password: AgCKHJ4cIv5SlYtGZvFQll5++00o14gL1M8a+2Fc2yxvqkZPUz5oxUKaPsDgSg8kae66UBWZDadhx40ellsdyf9qd6DBgxPeiSlnFPpS5p6uo0BUTAKyAHgIVs1HDu8vbZ0kYSLG3wEl5HwJmhceYnZ4Zg5m8K/HhlmwFUl+lmK8ruBJoPEOfd7n+2A33rEEdk3+8j6m0tFlksdyQ2gXRzOO1s3E075zNr3IR5zu9gj/7qcah/jgKnaFCV8KtGMuDOTpfCBvizkRLfurQz0W8yzNxojJaFElHgVgD151xj457EQxCk+TTD8IaSzAapY7l9puI1KPxS9j/TK3jQSScXGMbRqwIjoSpVZkuSgLXLAGyJPjwM3v7MWUOqeIBxVArIcsdDhMVlLtiMvViSRocKsgz+wmkyMTyCgLlvalC++8qcw6q6qtrGtoMImklyqTjr3bzskLjmgOjoQj9K1s7801KBVoTVP9VY5bHSTQxnprsHfZMsMstG/BPN/AlBnpzec9K2Xyehgv0kipJAHWJn2qDE7c6dyj4+Ks2r1Xs+h2YCjWAYuiqCzBLM4fb9MRiX5zuO4GvatmNiqIiJuxPeUdAwg7ULLJ/xzBVVYejihkbCwWU4X0DdjJh03zcyianY7J7G0xXrSKud9j/erREGrIMcToUeQZ7ij0l2ZU59ktg7Y6NBLj+bID1t3BY9sLJlfMzKgK
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dagster
        component: dbt-config
      name: postgresql-password
      namespace: dagster
    type: Opaque
