---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: datalab
spec:
  encryptedData:
    password: AgBwx2SgObYU5u0mC1mJpx18pMQvkpWf8ShbdnyfaaJ51ODSnDLCkWyZU0QHW4804NnTEimLBdHy2zDoCH2lQVkGnjbwBYBWrKptThggyAYnCsuJcsgVtLPENMLyirEireSbjLOHjcMKVtwo3clC67rbehZnT7iqU5uPy91mqPiSmn6TIXXJsTM0M5m3fXLofbl3m77olLpAAOPJkCaj6P16wcagmB3Zz45RgxrTqzzZYJuHS8L/GOak+BQ5ZsUoDnKReM5rQheJlDRB9xXyWHXa3mB4oTVr+2Fs1m4J6wqiVDtjRcuXb4+KQKT3tR0DS+mEJ67qiUC0WLMSgA692Al9BzWi9X/nmWNRcJXJ7XtnMdK/5MEon9yk1v6B17DbTJ4v4lh2FwT10xAgGqF7LOSCtKJ6+xx3vmB4aGOXw83/BpEx4M1cDYzX3zZeEX7YmZH6ay8HtQa7cMxmPgK/wjimGJRIG/UwJtWkGkC4NS+8778Mw+iPc/uRmEjOwJl4l4X5tvalxqLC7FUaNiGJk2kNoShVeEs3lzVZvwTAXNyrEHlvSL0kWJ4G5GrVRkWObX4bhXaCCK4WwWL6Uv9c+KYnMygUzMc18b40P2s6M1vAyFnNVZZiVGwSny3ymTCRedWq1x8D6lu8iRY5tNlLVpKKXHvJHhpu9h77XVhW+JX73euzDvye6Y4rpnE+4RRsPzkCB6fx
    postgres-password: AgCQsYcrt2NSGdny6Wcf/ghZuiMu20ucevtOwtB544f5E0TjflTduOCXy7KecaoPyO34it0G8XLcfMJom0kJAlvDHms47aMjexIrPIbVseTHy6aVPfe8JjIo13T5Db0aE8Zc198+Hmc3/hwJ7ICvzG4He54PoRQpY/CVJ3L4+N0xPWgiAU4zV/YKDDAjINgEHsMM0mlqz+8I1EpYKLDFc3wHNV7/n4Jb8Fjhad1TxYTTj12oYBHTQvkgOsy2jo8Rxk+4Rv6NtrukWdmPQCxwThtlroXxn4aDNVoJCid9Q5eB0h/IgLE2EKykoE8dN7w8tmc+jr26pUVIbs4DPPiJ95CqY5Vso22JEXx1Phba1oboSs90iPdd9tahvybbIjlvQ090DMK+75hHtgjs32rJrekphvi6k8SIGXUh+5WOcxkhPjmv2BhTXyLg2uVpTz3ephFn496fVVACFDvnf2lRf6aWetDg0fMVdLyDUPD6SiLWLEWkvPl8bygH553cabp9g1DpfGZdEmijGLyuI+iyHAXrpVgI2gB1jIdqJZmzyvgKKk0TY+5gp8w+A3ba3ns55o7mKPV6aKKA2gXqyBf03B1F0bQd3p8x2ukL5HmHIad0mFb57DfN+6Rl40weu2XHeTaGuTI0kgXXdil/9z/TlT/hn5XQEZ1/YZFKw7CKeFIUVPLh5fkWy8yCup9jqY9lHR5JO/8i
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: datalab
