---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pred-secrets
  namespace: selfhost
spec:
  encryptedData:
    SECRET_KEY: AgCqh8dwAOxDhFiF04a0MUhN7Eipr3umJV/IvLiriS7+FdNpqTPlHDdFnLt6yh6Y6CI5rOf+Rcsi59FTOvG97IbnDIaHAnJeQKtetxoiGNLcewYdKS4Iebk2W7/yRQNJqXUKgpWYSTwdAfsi55O78yFLhnlMsUzBAZ50e4pl70eQCbx1nWpv5uDIfjONl4vsDdjWCmg7AGTlzmFQ2cEjMiSJd1Yma669xZlmu+WRnf8ql/AFwGuvC4E54ihcYcMtRVZ9LeXoJinQglO9/BuxnS8QsGgJcIm+c4RSmDVruvhpyQ0PXClFcVmWmRz3fgi0IID15O6l/j9K4pmYBzWM/+D/9c9avjje/rcqoNADKmdn3tsHsR3rXUt0VKtcSnb0DyHv2oDolREoEkubcVgRs3heoSFjPg/Mz/d4YBPXni35N0rRhYecaDRm6nNq0vRjPfrx1RijyrmcdQWZtSr/qSz9A8dAERnbZyoMuPGRhm9kMvUEmU8SqxSY0zRs4x3IcpQ3nBXv4Y7fCS1Tzn4heAs8nSDgwC2mGJbDVfVTiUoRihmvV8bW9NYyoDRujGfkDhD6QfNkYlkU2BOIUfv//2SMLKxcyoDFl6ltbdi6Mk9J9gW7sqxMOCMi+VZWRum32QhWFhAAzRGZ4gV1WoB9/1M6puuaHXW8mJ1DLRAnO1WNLSSzdKj2WM5yVSJGW3IoFie9e2+hklJ3gbwmv5ueRl73pG6/KkQQOu4Eml5OfKwrfvfnMgiH+kvgCB8kshglaqviFQ==
  template:
    metadata:
      creationTimestamp: null
      name: pred-secrets
      namespace: selfhost
