---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pred-garmin
  namespace: selfhost
spec:
  encryptedData:
    GARMIN_EMAIL: AgBV9Eu8Yt1ribSv3Ft94pB0bm3Cbps2MR9t0TNXImb4ozC6dOZtQSbnIS/m/cFCM19WvUaOF6K3e5VNA5qC/wUp7S/FkVpWDJoivL47opi3UOYcRpE0wcwCd02/RiaRJ1ZN8JAdg7xILePYxyBsghgUPtUp+u+XzflRWvyflw5Z32rTHNJOnevn+xZ0lOiCK7qZOvn8urA13UnKwMEtj+3/NCaikz59C858y1lHUclOdPHcca25YkLYeHqBrTSRJ6l04pU5dclqT8zkMAJGHjcLNzMBs/E6o6/lORFjq89unxDhNdKCzwu/bbKe3ZLnsHymgfGzgdYcwAbbV8IMYC2KlCfZ3aFJ/x+jxyzFqTOX6AdFomoxvayvjn08NoBLlgVeF+7iRkQGq0XchwHYAxlQMflJRED9gMkgDPC7C229KoSecizhh75BmnKVCT6ZfDX/D48BUjcQRiJgzuhU7AXbY82qUpank/NFp7qvMf+t0GVqjWBfl2YnM9Pxy/fBfdSSIcckCQZW5AbVtnDaI4PTSY9AGjbmRg8mjRedvsV/hFwucMFVUNABdyYGyGKuw85kUkEnaFBPduAFpKOgVejJZ46zLrqUyI1TUcwf0C1NJwYWgzeUHkjHaMNViZTpg1dbaxJTOf5wQtP/7Mw1WC5YjAeNn/cJlvtULmvIuSO8vz++WLwAQC0hZWIdtOqVj/Muu5KkBOIjY/xr5zgUy0saOxqbew==
    GARMIN_PASSWORD: AgBjJ3f9eyfAhQ9dgAdE5JhQx99wgzA1PbCjxCr37PwQo/+V8AQyAw6GkcwJaIYYZ2Ln8QPs6wbAVJuHuGBQ1ZbiLdibtV5SsBB763x8IWmETMaiEUOQg1m6CKOZX2A6sWljwyHqtVM3cMLIb2gwB4Nj511sM8vQMS7crqFlLHPLF+z9JQDdntcqBs92XCi5yvGg8RusmyKHOXYw9e9M/M6/lWFs/rBj40x7flyf7Ty0T8Qt72LRlrzUEWouXhfm5+YBSWhRdGyEtP+vOiRUkhxa5kVYT0itbfycC90veQLUgx9yrhHJliXoswpiY/pIwxyG+HbCWzNXk9aLcaSnGYEz6yVZapdN818jXFka2gQfBgE6BxbXUuza/DrAr68T3oC5Q51a4Xn86ubjfcrDSUA3wFmA83I98e5OHsH5tAW7HxQEntW8ryJi3K+Tacp1YBY3qIdBKLu7lqZ3G28Us/ROsqYgAo1U+xOFQgGwde9NCxF1iRnoNSybjVJv0kfa3A0zc1zEi4W2jMmmeEqBMGiJ1jS4VoFajbUcFBOl5M7mKENjhru8cqCj8ACsfHQwTO+lqcqHrKLnrG9ywTh6vh1Ldo7HC4RInH5lQbGTmHcJBqFO5IPoImxv9W/hG3HmBRbMszu/3JJ3xO9vklhcRJ4Q2p9gIZxLeobZX6vpT/mrRw4gjL9+DBa/KcA3wOZm3VSNpehbccfcPw==
  template:
    metadata:
      creationTimestamp: null
      name: pred-garmin
      namespace: selfhost
