---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: recyclarr-api-keys
  namespace: selfhost
spec:
  encryptedData:
    RADARR_API_KEY: AgAH2+19GNBAUqCvAzKcY+njZehi8zVr8D8bApCXwrrZmwP8BK1ToPsKET21iCfQf545pGn+tq/rViyvva/cc6b5QROYRAg7lvD/yavCF11SkHTgzTtRqxhMsj6AKlMVO+nXb7iKekBR3l1n4s14Oa+trZKdPBXeaW3/v7V6+cuhItj1JC77SFmwXt4K78onPcx0cSe3C12sY3HcfpvyVHRR6P6qwJsRSjY8lxAPAMkVbAooWF6WEqagxeQn3GPA9MoxQVB8kLbxTCXietaKrzT7ea29RMbAEAoCDaimYODmYV26NwR2/OcfgmgpMFrxbdEPbq8/BUwWx19meGzJ+npwoH9LjU/kI2xdtaT9juOmcQLhZgjhcjckLvuBk2FJBtQ+cmYKivpFArG+/ZdKsjTS86m94GCz3Pxkjy518Uy51RnQ5hvH6no1DcsyrfuhCNWceb1WI5fzQciNm5Zs98utCdjM34qUB5KF7Bl9Qj1UjeltrN96mT8AU1hwnoEU1S876Yqbtt2CIVoA05rdpBD+1CdnFGQwN8wfosllJ1YzMB7/uBX1ckKhbUn1pJY0eHwjE8XP6BWelkwjUNgCGeLJ/xAvyIGRBRtMxC5E+Uy9Pj1CpAgF9GLT9dfj+niLxGZsK7YzIGdU6R1bsNtZErCiD3iM25NQNhN6BpN9hiEhlbvSrZVoEdXLc6X0ezvOGAqJNLWgX9kRnozl6sQr0bxalrB8YwROQN3MM0hCT6AM8Q==
    SONARR_API_KEY: AgANOC5kyoiwoG9+cuiseYFtBwsTFzdMVBNcQnU3j7Vce9pgxF47RaMux/LfgTJCowiXSeil+jD3BCjK+60uOAL9ax0VtRK0kW4V+n3K97iHiNOc6OqF+BiqFhHC3Ly5rC5vBxnna73hB2BdAQ4BLYZQ8WRD9x0SfFBJcSPGUOxuZ9ur7OyBuNzFNp4hojCAnHsDSHzH2nvOXnuUC26lfuCIL5kpq33yaZZhJdBrdsn6Z2jXlDF0I7WC8EhG8SkN9YPuIYEpKRzdcdRDJSRo8mlfIPM3bBHK/7zPKDrH7FRJa464UyIl+UPcSs/Y5sA62LVUgruiUKw/tGgVRMoEMofHcXaJcVaQUTBCAFEhYNVNQ3JP1TTz0OLnc3hjSo0hUA7fRaMWjon0teAw8aLpT6goN1DApRxRGZk5/DLxpxveShZ3m0XJTpn2RWks4WDpHa9RQsmK8K6sgG8eccWQ085LoefAmkSpneoqgLiaGN2E2zZ4kvxnfYTw89tgNJp4+H8GrIDxhhs9wvL8YGvPhvs5zDzOlZudM82uY9iyAkFyqb0Lt7KxZfb7COXOcszMVDMyJM/JIfWWjpcOdKDSfkTLPKDyR6S1TZaSu5/ufrXyjZZUUkPOlOQnFEAKkAiLOuuAUGejUlKE2Edg/H2IDH2G2E5WsGiJdSMtL9p/2ehrB9UJC3cs6jyJA/OIH+6cEIP361htIjDyM7upkntd6yuENFCQ8rn/BREuVF9iESMreg==
  template:
    metadata:
      creationTimestamp: null
      name: recyclarr-api-keys
      namespace: selfhost
    type: Opaque
