---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rsshub-secrets
  namespace: rsshub
spec:
  encryptedData:
    GITHUB_ACCESS_TOKEN: AgBqKgMt/SGPTsJt2eXVKBcnLTsvUg0HsOvKKZ6rd+mT6TPrwuhqQrkfsWi6sIuHWGroJPuM4N6YZ1mmN+y4i/8nqhEb9aezEv8FDZv5DKqwhITFJHJ4IbHQBxqwRD0yAbKpiW3WDeA/uawriX3toqTIxKpT4t7MIkeq6yvHFEQhBULqU2S9Cc9iMURLLEdM0FVGFCnxIFbjclH6nNyqe/zBikd8YDKgWUfzERWMOiCAxUwjHKO8LUKGiDP9oQnrH7RXq8e0lYrkTK3xpfCq1DUaRj4zrvq09KsW/iipt2ic/OOZQyIg64loMLC9sFaeiVIS3u3GbxQpDfGDYzBjEb7O5f2gI6/OeVSTsYcDzpgQoBfb+StPof8ZDvEdwgHLvHzp+0rudpFuR0Xy8f5ytVwMTWnR/MC8gA4ADqvWLr0ToCPDy1ggdCLEsu6y3+7OC8WlsexSSbY0NnfxmRkFYTOgXGcj3lNH4Ry1GYMjF3mSuP5kfZnEkgOcvx1MysbHUI65+Q+pwquI1ZJIG78ta4vrku0Ov/IvdtGYy5G3O6JxO5DSU1tXl2ou3GN6y5VMNTbeOOSbLsnL8Dlhn5Dg7yl6lImUVwThLP1qkKcRcEdbuzorR40/sPmifKSDipyY8vftBTbNziVpfgDOIhN2HWshE0ibHz7GQf7mqq8G7UFe9sHvkoinT6aT83ydVQZrTxGEK//ObP01tSDaSP5Dwrhf1tDvPaI/2XMuUj/wMfRjWYWL+qVIAsxsUtJiZY5K/xnskl+dLTsUKPv1vna3+bppBELwN509sRT8IcevUv5MBk9B3X3NbDhMwo8ZDBmc
  template:
    metadata:
      creationTimestamp: null
      name: rsshub-secrets
      namespace: rsshub
