---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rsshub-secrets
  namespace: rsshub
spec:
  encryptedData:
    GITHUB_ACCESS_TOKEN: AgCduHOm/YenyQmeD0xUMusRLb3jxY2L4gte0NAilFZKAe9AyHZOiXifJr9W5GQhVTo9CdzhZr6Y4l6H0PdEXqp/ww6WAhRH5ZnUpyWEo02GvPn3pHyIEgoU+Tynbu0LZ7RXOQIOlKWePzhsKJU0y3X2ecabBpzszlJIy2EUmarmW5VQuqItIHAlNX3UqnXsjAuh5AmiLlJetxMcSWf36GOK8pKvpgg0Ej/BKYDqasT8oaMxVVKtORii59irxvao3tKQuN7X1P9JOMEH4bFl37UJM+YrivwswUsUUn50cz28zu1bO3bLFoccXG3YhatubQG0SL5q5x9cNmEG9aUTRt+MpZEmVSVNp4XhWpCaXlg8U2/4HPIPrRv6tuyN57HrvgLH/hgEj1HzdA34AK+lZO64uzOUtJbc/YuqJ9MAA52XXu0vHHIckAasnln7KfkCpbPpgF98vKhd70VAmp//2MZQdmkdFUNKvx5nq0GtAwy4w2vsdS5BO04IVoudJqxaW10q1LefqG43BBQFM/10mxtJgalRqkHiBfuHCgid3gn1/ABZqf6dE1Hqck8kKB9/gbOD+LEqyJVC72VYzo1aKdo13BaTLE49FmpQwM/tZQU4kvs0vR5GKauMvLBsLrpJSWPsERU2VfBoVLdVe785zSyIv9eoJ9TBz4By2nZFG2k/ldNcE+bk9PZ/DddQuTa1bL2a32n1cSFzmyV+PG1MliUC7KublKv/Q6xsI7404pnbbfRG4KZKxakjXppJX7CsFfWJxYM5M9cTV390nDpdKE62YCGuWPUywvyToMMAEG4yXxm1bQaXDMK9qfCdCpI=
  template:
    metadata:
      creationTimestamp: null
      name: rsshub-secrets
      namespace: rsshub
