---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-claude-traefik-header
  namespace: ingress
spec:
  encryptedData:
    web-claude.yml: AgBxACWK+seWuAD1yWNNj+CrvUDSjnzYYnB2S/UGQ9CKN0fFDw2n3xPtzGUYLjYBnNvZUKHlsTBy0CfnerJjo3I+O5fMfNNLTJZ85eihEg6g4XA7WoPzsAN4SWyIyZsPDJ4zgttG7P9XJoNX+8dVwSE2Jc2eDFrjadJC7zPA8tolvdHTUSmfKlt/ZvvVZo6fjetQiuTlf5xurwwNclS0seUCLgoqSaCM8pl1+Rb4fffwvYpsX34oxbaW24w0nvrNDnN/JsngutsLngV30jvw9lVuCpQcy6ivYoyEfxcU8GwzaKN9huY1tp/+BGvacFWvmf7buioTO41Zda8RyOTQPcp+utMgvJjy0WzTMbWuaXJeDSY4DIK8xPNwWA6yPFYK3L/aAIRfVOE0nb8Ss4YRZdpIS+oDMamKzBHq/f/PEO+jydMCIA6Mmz5eG6+EHDCsSid0GUT7yxq9dV92IQGCmbrrAjCTay9ZM5yLraipJB8ptOm7uFdlflriU1sJ8O3Nnv7+M0AosVbxgZCFmZbcCUP2pTHFVHABsyQ8GQkZrM/VuEtAuihjwmipsIBMAuaJfnaMPG4P9CbvhbAD2Ijf0Ccw8oJkFmzBrams3+FYTe0weDOrxkLOCgwX+irEQzLecJv2moZdr9ZoGwWFaJa3gJQr/XRkJMLm/eOMFMjkCa91BbDvW0rEVPhAcKUmD5Ah9YbDJM6tdzhXXFkLfTV8HKBOqWHQ44AA0cnycpovh55w+6xGBqsD/5fX4Qy+eL80l5FUHfMkk4ZIZX8kMDAEvzyBuNKRiAzLJtIYM4xaHhBxze8BWCtdz1FeZRJMZJ2hJeIt3rqx2KYIFT0QL3pCQfzXcZ1vbnK2FMXHypFc/GtkDkUBTA1uBJKiykher3kZ3UxoRbQw7yP6NElex+NpVJxFxvnPeSN06+5Uaco4VlvMc5O6qRgbYt4LfNAesNZg/rE0Td8adUYG0vQiT9zmJt/33C7gWU51g03PYVgXPlRG9l7kglrAI71sensxyQn4svAyX4gBdkjlHUPNdL+UWrug3oQyN6l7VQ9+3TkvOpVlJBLjhBo5e/RwgLXf4SLWTmQ5B0wmtOOxywpq8GxjgkE1g69xDQK23W3AOMUTMaiX2gLPCzyPoQRMfrIUg0sMFRJkjUhnO/CVPeyDoTR9TRLibxdSkIJric/ipwe0cRCEtGMkpP7gtjCxfl5YC4CZs10qKhzTQXS1Xi1H3/mXHpR3/bkLr+3N3FFcjUxEiBz3oZfex+fYTQl4tzdqZHfFMKCCR2fxyAtTi5y5nlykll5AP7OT3Em6J9yP/wW7Kc1Ar0f5C9xfQCAFXQJvRMqukmI5Z2ZFdw8ykCbzUGsyOZitVIxEOCRjLyvHKborm64WB5vBBg==
  template:
    metadata:
      creationTimestamp: null
      name: web-claude-traefik-header
      namespace: ingress
