apps:
  sonarr:
    main:
      base_url: http://sonarr.selfhost.svc.cluster.local:8989
      download_clients:
        prune: false
        items:
          - name: qBittorrent
            enable: true
            protocol: torrent
            priority: 1
            implementation: QBittorrent
            configContract: QBittorrentSettings
            fields:
              - name: host
                value: qbittorrent.selfhost.svc.cluster.local
              - name: port
                value: 8080
              - name: useSsl
                value: false
              - name: urlBase
                value: ''
              - name: tvCategory
                value: sonarr
              - name: tvImportedCategory
                value: ''
              - name: recentTvPriority
                value: 0
              - name: olderTvPriority
                value: 0
              - name: initialState
                value: 0
              - name: sequentialOrder
                value: false
              - name: firstAndLast
                value: false
              - name: contentLayout
                value: 0
            tags: []
            removeCompletedDownloads: true
            removeFailedDownloads: true
