apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: datalab
spec:
  project: default
  source:
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: main
    path: kubeflow/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: datalab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
