apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configarr.fullname" . }}
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ .Files.Get "files/config.yml" | indent 4 }}
