apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "configarr.fullname" . }}
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "configarr.selectorLabels" . | nindent 12 }}
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        spec:
          restartPolicy: Never
          containers:
            - name: configarr
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              tty: true
              env:
                - name: TZ
                  value: {{ .Values.timezone | quote }}
              envFrom:
                - secretRef:
                    name: {{ .Values.apiKeysSecret }}
              volumeMounts:
                - name: config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
                - name: cache
                  mountPath: /app/repos
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: config
              configMap:
                name: {{ include "configarr.fullname" . }}
            - name: cache
              persistentVolumeClaim:
                claimName: {{ include "configarr.fullname" . }}-cache
