apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "configarr.fullname" . }}-env
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.akeyless.secretStoreName }}
  target:
    name: {{ include "configarr.fullname" . }}-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.akeyless.apiKeysPath }}
