apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "configarr.fullname" . }}-cache
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.cache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
