apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.akeyless.secretStoreName }}
  labels:
    {{- include "configarr.labels" . | nindent 4 }}
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://api.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: {{ .Values.akeyless.credsSecret }}
            key: accessId
          accessType:
            name: {{ .Values.akeyless.credsSecret }}
            key: accessType
          accessTypeParam:
            name: {{ .Values.akeyless.credsSecret }}
            key: accessTypeParam
