apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 14.0.13
    chart: airflow
    helm:
      values: |
        auth:
          password: Passw0rd
        git:
          dags:
            enabled: true
            repositories:
              - repository: "https://github.com/tom333/accidentologie_nc.git"
                branch: "main"
                name: "accidentologie_nc"
                path: "airflow"
        ingress:
          enabled: true
          ingressClassName: pomerium
          hostname: airflow.tgu.ovh
          path: /*
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingress.pomerium.io/allowed_users: |
              - laboitatom@gmail.com
            ingress.pomerium.io/allow_any_authenticated_user: 'true'
            ingress.pomerium.io/allow_websockets: 'true'
          tls: true

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
