apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 14.0.12
    chart: airflow
    helm:
      values: |
        #executor: KubernetesExecutor
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingress.pomerium.io/allowed_users: |
              - laboitatom@gmail.com
            ingress.pomerium.io/allow_any_authenticated_user: 'true'
            ingress.pomerium.io/allow_websockets: 'true'
          ingressClassName: "pomerium"
          hostname: airflow.tgu.ovh
          tls: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
