apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://airflow.apache.org/"
    targetRevision: 1.8.0
    chart: airflow
    helm:
      values: |
        auth:
          username: user
          password: PasswOrd
        ingress:
          web:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              ingress.pomerium.io/allowed_users: |
                - laboitatom@gmail.com
              ingress.pomerium.io/allow_any_authenticated_user: 'true'
              ingress.pomerium.io/allow_websockets: 'true'
            ingressClassName: "pomerium"
            host: airflow.tgu.ovh
            hosts:
              - name: airflow.tgu.ovh
                tls:
                  enabled: true
                  secretName: airflow-web-tls
            tls:
              enabled: true
              secretName: airflow-web-tls
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
