apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-applicationset
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: '1.6.0'
    chart: argocd-applicationset
  project: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

