apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arrconf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhost
    server: https://kubernetes.default.svc
  project: selfhost-project
  source:
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: HEAD
    path: charts/arrconf
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
