apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.authelia.com
    chart: authelia
    targetRevision: 0.10.12
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls:
            enabled: true
          hostOverride:
            - host: 'authelia.tgu.ovh'
              path: '/'
        configMap:
          storage:
            local:
              enabled: true
            postgres:
              enabled: false
          session:
            cookies: 
              - domain: tgu.ovh
                subdomain: authelia
          authentication_backend:
            file:
              enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
