apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://adwerx.github.io/charts/"
    targetRevision: 3.4.3
    chart: awx
    helm:
      parameters:
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0]
          value: "awx.home.lan"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
