apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhosted
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: calibre-web/
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: main
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/proxy-body-size: "512m"
          hosts:
            - host: calibre.tgu.ovh
              paths:
                - path: /
                  pathType: Prefix
                  overrideService:
                    name: calibre-web
                    port: 8083
          tls:
            - hosts:
                - calibre.tgu.ovh
              secretName: calibre-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true