apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: main
    path: kubeflow/certificates/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
