apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://aureq.github.io/cert-manager-webhook-ovh/
    targetRevision: 0.7.5
    chart: cert-manager-webhook-ovh
    helm:
      values: |
        groupName: tgu.ovh
        issuers:
          - name: letsencrypt-prod-dns
            create: true
            kind: ClusterIssuer
            email: laboitatom@gmail.com
            ovhAuthenticationRef:
              applicationKeyRef:
                name: ovh-credentials
                key: applicationKey
              applicationSecretRef:
                name: ovh-credentials
                key: applicationSecret
              consumerKeyRef:
                name: ovh-credentials
                key: consumerKey
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    automated:
      selfHeal: true
      prune: true
