apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.12.0
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: prometheus.enabled
          value: "false"
        - name: webhook.timeoutSeconds
          value: "4"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
