apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: che
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eclispe-che
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://eclipse-che.github.io/che-operator/charts"
    targetRevision: 7.60.1
    chart: eclipse-che

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
