ingress:
  app:
    enabled: "true"
    hostName: "app.clearml.tgu.ovh"
  api:
    enabled: "true"
    hostName: "api.clearml.tgu.ovh"
  files:
    enabled: "true"
    hostName: "files.clearml.tgu.ovh"
    annotations: { nginx.ingress.kubernetes.io/proxy-body-size: "128m" }
