apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-serving
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://allegroai.github.io/clearml-helm-charts"
    targetRevision: 0.7.0
    chart: clearml-serving
    helm:
      values: |
        clearml:
          apiAccessKey: "BJ0R89334KG6PYD8G693"
          apiSecretKey: "GJASTFeIfghAyQmF1Hp4p9yQq6pc3UtmVZZYFbLtV7E9MllDNa"
          apiHost : http://clearml-apiserver.datalab.svc.cluster.local:8008
          filesHost: http://clearml-fileserver.datalab.svc.cluster.local:8081
          webHost: http://clearml-webserver.datalab.svc.cluster.local:8080
          defaultBaseServeUrl: https://serve.clearml.tgu.ovh
        clearml_serving_triton:
          ingress:
            enabled: true
            hostName: serving-grpc.clearml.tgu.ovh
            tlsSecretName: "clearml-serving-tls"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              ingress.pomerium.io/allowed_users: |
                - laboitatom@gmail.com
              ingress.pomerium.io/allow_websockets: 'true'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
