apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://allegroai.github.io/clearml-helm-charts"
    targetRevision: 3.7.0
    chart: clearml-agent
    helm:
      values: |
        agentk8sglue:
          apiServerUrlReference : clearml-apiserver.datalab.svc.cluster.local
          fileServerUrlReference: clearml-fileserver.datalab.svc.cluster.local
          webServerUrlReference: clearml-webserver.datalab.svc.cluster.local
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true