apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://allegroai.github.io/clearml-helm-charts"
    targetRevision: 4.0.7
    chart: clearml-agent
    helm:
      values: |
        clearml:
          agentk8sglueKey: "BJ0R89334KG6PYD8G693"
          agentk8sglueSecret: "GJASTFeIfghAyQmF1Hp4p9yQq6pc3UtmVZZYFbLtV7E9MllDNa"
        agentk8sglue:
          apiServerUrlReference : http://clearml-apiserver.datalab.svc.cluster.local:8008
          fileServerUrlReference: http://clearml-fileserver.datalab.svc.cluster.local:8081
          webServerUrlReference: http://clearml-webserver.datalab.svc.cluster.local:8080
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
