apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: clickhouse
    targetRevision: 6.3.2
    helm:
      values: |
        ingress:
          enabled: true
          hostname: clickhouse.tgu.ovh
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          pathType: ImplementationSpecific
          hosts:
            - host: clickhouse.tgu.ovh
              paths:
                - /
          tls: true
          secret: clickhouse-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true