apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: 'ci/helm-chart'
    repoURL: 'https://github.com/cdr/code-server'
    targetRevision: 'HEAD'
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
      valueFiles:
        - https://raw.githubusercontent.com/tom333/argocd_kluster/main/argocd/argocd-apps/code-server-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true