apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ci/helm-chart
    repoURL: https://github.com/coder/code-server.git
    targetRevision: v4.90.0
    helm:
      values: |
        image:
          repository: tom333/coder
          tag: 'latest'
          pullPolicy: Always
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: code.tgu.ovh
              paths:
                - /
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://code.tgu.ovh"
          tls:
            - hosts:
                - code.tgu.ovh
              secretName: code-tls
        extraArgs:
          - --auth
          - none
        extraVars:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.datalab.svc.cluster.local:5000
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://minio.datalab.svc.cluster.local:9000
          - name: DISABLE_TELEMETRY
            value: "true"
          - name: DOCKER_HOST
            value: "tcp://localhost:2375"
        extraContainers: |
          - name: docker-dind
            image: docker:19.03-dind
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 250m
                memory: 256M
            securityContext:
              privileged: true
              procMount: Default
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ""
              - name: DOCKER_DRIVER
                value: "overlay2"
        extraInitContainers: |
          - name: customization
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            env:
              - name: SERVICE_URL
                value: "https://open-vsx.org/vscode/gallery"
              - name: ITEM_URL
                value: "https://open-vsx.org/vscode/item"
            command:
              - sh
              - -c
              - |
                code-server --install-extension ms-python.python GitHub.vscode-pull-request-github ms-kubernetes-tools.vscode-kubernetes-tools
            volumeMounts:
              - name: data
                mountPath: /home/coder

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
