apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ci/helm-chart
    repoURL: https://github.com/coder/code-server.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: tom333/coder
          tag: 'latest'
        ingress:
          enabled: true
          ingressClassName: pomerium
          hosts:
            - host: code.tgu.ovh
              paths:
                - /
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            # ingress.pomerium.io/allowed_users: |
            #   - laboitatom@gmail.com
            # ingress.pomerium.io/allow_any_authenticated_user: 'true'
            # ingress.pomerium.io/allow_websockets: 'true'
            ingress.pomerium.io/allow_public_unauthenticated_access: 'true'
          tls:
            - hosts:
                - code.tgu.ovh
              secretName: code-tls
        extraArgs:
          - --auth
          - none
        extraVars:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.datalab.svc.cluster.local:5000
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://minio.datalab.svc.cluster.local:9000
        # extraInitContainers:
        #   - name: customization
        #     image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        #     imagePullPolicy: IfNotPresent
        #     env:
        #       - name: SERVICE_URL
        #         value: https://open-vsx.org/vscode/gallery
        #       - name: ITEM_URL
        #         value: https://open-vsx.org/vscode/item
        #     command:
        #       - sh
        #       - -c
        #       - |
        #         code-server --install-extension ms-python.python
        #     volumeMounts:
        #       - name: data
        #         mountPath: /home/coder

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
