apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://helm.coder.com"
    targetRevision: 1.39.1
    chart: coder
    helm:
      values: |
        coderd:
          devurlsHost: "*.lab.tgu.ovh"
          # tls:
          #   hostSecretName: wildcard-tgu-ovh-mjzvx
          #   devurlsHostSecretName: wildcard-tgu-ovh-mjzvx
          serviceSpec:
            # The Ingress will route traffic to the internal ClusterIP.
            type: ClusterIP
            externalTrafficPolicy: ""
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          host: coder.tgu.ovh

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
