ingress:
  enabled: true
  hosts:
    - host: code.home.lan
      paths:
        - path: '/'
          pathType: Prefix
          backend:
            service:
              name: code-server
              port:
               number: 8080