apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cv
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: mycv/
    repoURL: https://github.com/tom333/cv.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
