apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dagster
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://dagster-io.github.io/helm
    targetRevision: 1.12.13
    chart: dagster
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://dagster.tgu.ovh"
          dagsterWebserver:
            host: dagster.tgu.ovh
            path: /
            pathType: Prefix
            tls:
              enabled: true
              secretName: dagster-tls
        dagsterWebserver:
          workspace:
            enabled: false

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
