apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub-prerequisites
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datahub
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.datahubproject.io/
    targetRevision: 0.1.15
    chart: datahub-prerequisites
    helm:
      values: |
        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: datahub
                password: datahub
                database: datahub
          image:
            registry: docker.io
            repository: bitnamilegacy/postgresql
            tag: 14.3.0-debian-11-r5

        mysql:
          enabled: false
        elasticsearch:
          # set this to false, if you want to provide your own ES instance.
          enabled: false
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub-elastic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datahub
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: elasticsearch
    helm:
      values: |
        replicas: 1
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datahub
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.datahubproject.io/
    targetRevision: 0.6.21
    chart: datahub
    helm:
      values: |
        datahub-frontend:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - host: datahub.tgu.ovh
                path: /
            tls:
              - secretName: datahub-tls
                hosts:
                  - datahub.tgu.ovh
        mysqlSetupJob:
          enabled: false
        postgresqlSetupJob:
          enabled: true
        global:
          kafka:
            bootstrap:
              server: "datahub-prerequisites-kafka:9092"
            zookeeper:
              server: "datahub-prerequisites-zookeeper:2181"
          elasticsearch:
            host: "elasticsearch-master"
          sql:
            datasource:
              host: "datahub-prerequisites-postgresql:5432"
              hostForpostgresqlClient: "datahub-prerequisites-postgresql"
              port: "5432"
              url: "jdbc:postgresql://datahub-prerequisites-postgresql:5432/datahub"
              driver: "org.postgresql.Driver"
              username: "datahub"
              password:
                value: datahub
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
