apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datahub
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.datahubproject.io/
    targetRevision: 0.1.15
    chart: datahub-prerequisites
    helm:
      values: |
        postgresql:
          enabled: true
        mysql:
          enabled: false
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
