apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: dremio
    targetRevision: 0.1.13
    helm:
      values: |
        ingress:
          enabled: true
          hostname: dremio.tgu.ovh
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          pathType: ImplementationSpecific
          hosts:
            - host: dremio.tgu.ovh
              paths:
                - /
          tls: true
          secret: dremio-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true