apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emby
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: jellyfin
  source:
    path: ""
    repoURL: https://pmoscode-helm.github.io/emby/
    targetRevision: 1.3.0
    chart: emby
    helm: 
      values: | 
        ingress:
          enabled: true
          className: nginx
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: emby.tgu.ovh
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: emby-tls
              hosts:
                - emby.tgu.ovh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emby-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: https://mage-ai.github.io/helm-charts
    targetRevision: 0.0.1
    chart: emby-ingress
    helm: 
      values: | 
        ingress:
          name: emby
          enabled: true
          className: ""
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://emby.tgu.ovh"
          hosts:
            - host: emby.tgu.ovh
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: emby
                      port: 6789
          tls: 
            - secretName: mage-tls
              hosts:
                - emby.tgu.ovh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
