apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.5.2
    chart: fluentd
    helm: 
      values: | 
        ingress:
          enabled: true
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://code.tgu.ovh"
              
          hosts:
            - host: fluentd.tgu.ovh
            - port: 9880

          tls: []
          - secretName: fluentd-tls
            hosts:
              - fluentd.tgu.ovh

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
