apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhost
    server: https://kubernetes.default.svc
  project: selfhost-project
  source:
    repoURL: tccr.io/truecharts
    targetRevision: 21.12.6
    chart: freshrss
    helm:
      values: |
        ingress:
          main:
            enabled: false
            ingressClassName: nginx
            targetSelector:
              main: main
            hosts:
              - host: freshrss.tgu.ovh
                paths:
                  - path: /
                    pathType: Prefix
                    overrideService:
                      name: main
                      port: 80
            tls:
              - hosts:
                  - freshrss.tgu.ovh
                secretName: freshrss-tls
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
