apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhost
    server: https://kubernetes.default.svc
  project: selfhost-project
  source:
    repoURL: https://rubxkube.github.io/charts/
    targetRevision: 1.2.11
    chart: freshrss
    helm:
      values: |
        common: 
          ingress:
            enabled: true
            hostName: freshrss.tgu.ovh
            tls:
              enabled: true
              secretName: freshrss-tls-secret
            entrypoint: websecure
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
