apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kybe-system
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: v4.11.3
    chart: ingress-nginx
    helm:
      values: |
        fullnameOverride: ingress-nginx
        controller:
          kind: DaemonSet
          hostNetwork: true
          hostPort:
            enabled: true
          service:
            enabled: true
            loadBalancerIP: "192.168.1.250"
          publishService:
            enabled: false
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false
          config:
            use-forwarded-headers: "true"
          setAsDefaultIngress: true
          ingressClass:
              setAsDefaultIngress: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
