apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.1.0
    chart: jellyfin
    helm: 
      values: | 
        ingress:
          enabled: true
          className: nginx
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: jellyfin.tgu.ovh
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: jellyfin-tls
              hosts:
                - jellyfin.tgu.ovh
        jellyfin:
          enableDLNA: true
        # volumes: 
        #   - name: nas
        #     csi:
        #       driver: smb.csi.k8s.io
        #       volumeAttributes:
        #         source: //192.168.2.103/public 
        #         secretName: smbcreds-secret
        # volumeMounts: 
        #   - name: nas
        #     mountPath: /media/nas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
