apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  destination:
    namespace: jupyter
    server: https://kubernetes.default.svc
  project: jupyter-project
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "3.0.2"
    chart: jupyterhub
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/tom333/my-kluster/main/argocd/argocd-apps/jupyterhub-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
