apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  destination:
    namespace: jupyter
    server: https://kubernetes.default.svc
  project: jupyter-project
  source:
    path: ''
    repoURL: 'https://jupyterhub.github.io/helm-chart/'
    targetRevision: 1.2.0
    chart: jupyterhub
    helm:
      values: |
        singleuser:
          defaultUrl: "/lab"
          extraEnv:
            JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
          image: jupyter/tensorflow-notebook
          tag: python-3.8.8
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true