singleuser:
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
  image:
    name: elyra/elyra
    tag: 3.13.0
  storage:
    dynamic:
      storageClass: nfs-dynamic
ingress:
  enabled: false
  annotations:
    cert-manager.io/issuer: letsencrypt
  hosts:
    - jupyter.tgu.ovh
  tls:
    - secretName: letsencrypt
      hosts:
        - jupyter.tgu.ovh
cull:
  enabled: false
# proxy:
#   service:
#     type: ClusterIP
#   https:
#     enabled: true
#     hosts:
#       - "jupyter.tgu.ovh"
#     letsencrypt:
#       contactEmail: "laboitatom@gmail.com"
# hub:
#   config:
#     GoogleOAuthenticator:
#       client_id: 434813270748-gotip87nh52h0ksn104ckg0g84d32670.apps.googleusercontent.com
#       client_secret: yGOCSPX-uHtqfDAgIlggd3Be2tAZxYJMt_KH
#       oauth_callback_url: https://jupyter.tgu.ovh/hub/oauth_callback
#       hosted_domain:
#         - jupyter.tgu.ovh
#       login_service: Jupyterlab
#     JupyterHub:
#       authenticator_class: google
