apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhosted
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.truecharts.org
    chart: kavita
    targetRevision: 11.2.3
    helm:
      values: |
        ingress:
          main:
            enabled: false
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            targetSelector:
              main: main
            hosts:
              - host: kavita.tgu.ovh
                paths:
                  - path: /
                    pathType: Prefix
                    overrideService:
                      name: main
                      port: 80
            tls:
              - hosts:
                  - kabita.tgu.ovh
                secretName: kavita-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true