apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 24.6.1
    chart: keycloak
    helm:
      values: |
        replicas: 1
        ingress:
          enabled: true
          hostname: auth.tgu.ovh
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls: true
          secret: keycloak-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
