apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://codecentric.github.io/helm-charts"
    targetRevision: 18.10.0
    chart: keycloak
    helm:
      values: |
        # image:
        #   # We use the legacy variant of the image until codecentric update it's helm chart
        #   tag: "18.0.2-legacy"
        replicas: 1
        ingress:
          enabled: true
          servicePort: http
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          rules:
            - host: "auth.tgu.ovh"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - auth.tgu.ovh
              secretName: keycloak-tls
        postgresql:
          postgresqlPassword: Passw0rd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
