apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: komga
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: komga
    targetRevision: 0.0.1
    helm:
      values: |
        common: 
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hostName: komga.tgu.ovh
            tls:
              enabled: true
              secretName: chart-example-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true