apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-knative
  namespace: argocd
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: kubeflow-knative
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
