apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: apps/
    repoURL: https://github.com/tom333/argocd-kubeflow.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
