apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-dependencies
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: dependencies/
    repoURL: https://github.com/tom333/argocd-kubeflow.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
