apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: https://kubetail-org.github.io/helm-charts/
    targetRevision: 0.9.5
    chart: kubetail
    helm: 
      values: | 
        kubetail: 
          server: 
            ingress:
              enabled: true
              annotations: 
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
                nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
                nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://fluentd.tgu.ovh"   
              rules: 
                - host: kubetail.tgu.ovh
                  http:
                    paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: kubetail-server
                          port:
                            number: 4000
              tls: 
                - secretName: kubetail-tls
                  hosts:
                    - kubetail.tgu.ovh

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
