apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: apps/
    repoURL: https://github.com/tom333/argocd-kubeflow.git
    targetRevision: HEAD
  kustomize:
    version: v3.2.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
  ignoreDifferences:
    - kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks"
    - kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks[]?.clientConfig"
    - kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/1/clientConfig/caBundle
    - kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/2/clientConfig/caBundle
    - kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks"
