apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: apps/
    repoURL: https://github.com/tom333/argocd-kubeflow.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - .rules
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhookClientConfig.caBundle
