apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://tom333.github.io/my-charts
    targetRevision: 1.0.10
    chart: datalab   
    helm:
      values: |
        mariadb:
          startupProbe:
            enabled: true
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
            successThreshold: 1
            periodSeconds: 10
          livenessProbe:
            enabled: true
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          readinessProbe:
            enabled: true
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
