apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ia-lab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://tom333.github.io/my-charts
    targetRevision: 1.5.0
    chart: datalab
    helm: 
      values: | 
        global:
          security: 
            allowInsecureImages: true
        rustfs:
          mode:
            standalone:
              enabled:  true
            distributed:
              enabled: false
          ingress:
            nginxAnnotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
          storageclass: 
            name: microk8s-hostpath
        mlflow:
          mlflow:
            database:
              hostname: "lab-postgresql"
        postgresql:
          auth:
            username: "ducklake"
            password: "ducklake"
            database: "ducklake"
          primary:
            initdb:
              scripts:
                00_init_database.sql: |
                  DO
                  $$
                  BEGIN
                     IF NOT EXISTS (
                        SELECT FROM pg_catalog.pg_roles 
                        WHERE rolname = 'mlflow'
                     ) THEN
                        CREATE ROLE mlflow LOGIN PASSWORD 'mlflow';
                     END IF;
                  END
                  $$;
                  
                  SELECT 'CREATE DATABASE mlflow OWNER mlflow'
                  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mlflow')\gexec
                  
                  GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflow;
        

    # path: zenml/
    # repoURL: https://github.com/tom333/my-kluster.git
    # targetRevision: HEAD
    # kustomize:
    #   patches:
    #     - target:
    #         kind: Deployment
    #         name: lab-zenml
    #       patch: |-
    #         - op: replace
    #           path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
    #           value: 90
    #         - op: replace
    #           path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
    #           value: 90

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
    automated:
      selfHeal: true
      prune: true

