apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://tom333.github.io/my-charts
    targetRevision: 1.0.10
    chart: datalab   

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
