apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: datalab-chart/
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: lab-zenml
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
              value: 60
            - op: replace
              path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
              value: 60

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
