apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakefs
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://charts.lakefs.io"
    targetRevision: 0.8.7
    chart: lakefs
    helm:
      values: |
        ingress:
          enabled: true
          annotations: {}
          ingressClassName: ""
          defaultBackend: {}
          hosts:
            - host: lakefs.tgu.ovh
              paths:
                - /
        lakefsConfig: |
          database:
            type: local
          blockstore:
            type: s3
            s3:
              force_path_style: true
              endpoint: http://minio.datalab.svc.cluster.local:9000
              credentials:
                access_key_id: "admin"
                secret_access_key: Passw0rd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
