apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mageai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: https://mage-ai.github.io/helm-charts
    targetRevision: 0.2.6
    chart: mageai
    helm: 
      values: | 
        persistence:
          enabled: false  
        image:
          repository: mageai/mageai
          pullPolicy: Always
          # Overrides the image tag whose default is the chart appVersion.
          tag: latest  

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mageai-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: https://mage-ai.github.io/helm-charts
    targetRevision: 0.0.1
    chart: mageai-ingress
    helm: 
      values: | 
        ingress:
          name: mageai
          enabled: true
          className: ""
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://mageai.tgu.ovh"
          hosts:
            - host: mageai.tgu.ovh
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: mageai
                      port: 6789
          tls: 
            - secretName: mage-tls
              hosts:
                - mageai.tgu.ovh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
