apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: charts/mariadb/
    repoURL: https://github.com/InseeFrLab/helm-charts-databases.git
    targetRevision: main
    helm:
      values: |
        mariadb:
          auth:
            rootPassword: password
            database: zenml
            username: zenml
            password: zenml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
