apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaflow
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://github.com/outerbounds/metaflow-tools
    path: k8s/helm/metaflow
    targetRevision:  HEAD
    helm:
      values: |
        metaflow-ui:
          metadatadb:
            password: metaflow
            name: metaflow
            user: metaflow
          ingress:
            enabled: true
            hosts:
              - host: metaflow.tgu.ovh

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
