apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 17.0.5
    chart: minio
    helm:
      values: |
        replicas: 1
        mode: standalone
        persistence:
          size: 10Gi
        existingSecret: minio-secret
        apiIngress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hostname: minio.tgu.ovh
          tls: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/ingress.allow-http: "false"
          hostname: minio-console.tgu.ovh
          tls: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
