apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 12.1.3
    chart: minio
    helm:
      values: |
        auth:
          existingSecret: minio-secret
        ingress:
          enabled: true
          hostname: minio.tgu.ovh
          tls: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "128m"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
        apiIngress:
          enabled: true
          hostname: minio-api.tgu.ovh
          tls: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "128m"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
        extraEnvVars:
          - name: MINIO_API_CORS_ALLOW_ORIGIN
            value: "'*'"
          - name: MINIO_IDENTITY_OPENID_CONFIG_URL
            value: "https://auth.lab.tgu.ovh/auth/realms/datalab/.well-known/openid-configuration"
          - name: MINIO_IDENTITY_OPENID_CLIENT_ID
            value: minio
          - name: MINIO_DOMAIN
            value: "minio-api.tgu.ovh"
          - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
            value: https://minio.tgu.ovh/oauth_callback
          - name: MINIO_IDENTITY_OPENID_SCOPES
            value: openid, profile, email, roles
          - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
            value: /secrets/auth-creds/keycloak-client-id
          - name: MINIO_IDENTITY_OPENID_CLIENT_ID
            value: minio
        extraVolumeMounts: |
          - name: auth-creds
            mountPath: /secrets/auth-creds
            readOnly: true
        extraVolumes: |
          - name: auth-creds
            secret:
              secretName: minio-secret

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
