apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 11.10.19
    chart: minio
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/tom333/my-kluster/main/argocd/argocd-apps/minio-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
