auth:
  rootPassword: UGFzc3cwcmQ=
ingress:
  enabled: true
  hostname: minio.tgu.ovh
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
apiIngress:
  enabled: true
  hostname: minio-api.tgu.ovh
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
