apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 3.0.7
    chart: mlflow
    helm:
      values: |
        run:
          persistence:
            enabled: true
        tracking:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/proxy-body-size: 512m
              nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://mlflow.tgu.ovh"
            hostname: mlflow.tgu.ovh
            tls: true
        postgresql:
          auth:
            password: password
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
