apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://community-charts.github.io/helm-charts"
    targetRevision: 0.8.13
    chart: mlflow
    helm:
      parameters:
        - name: postgresqlPassword
          value: "password"
        - name: postgresqlDatabase
          value: "mlflow"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
