apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.1.0
    chart: mlflow
    helm:
      values: |
        strategy:
          type: Recreate

        extraVolumes:
          - name: mlflow-volume
            persistentVolumeClaim:
              claimName: mlflow-pvc

        extraVolumeMounts:
          - name: mlflow-volume
            mountPath: /mlflow/data

        backendStore:
          defaultSqlitePath: "/mlflow/data/mlflow.db"

        artifactRoot:
          proxiedArtifactStorage: true
          defaultArtifactsDestination: "/mlflow/data/mlartifacts"

        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/proxy-body-size: 512m
            # nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            # nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://mlflow.tgu.ovh"
          hosts:
            - host: mlflow.tgu.ovh
              paths:
              - path: /
                pathType: ImplementationSpecific
          tls:
             secretName: mlflow-tls
             hosts:
               - mlflow.tgu.ovh
        auth:
          enabled: false
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
