apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-zenml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 13.0.3
    chart: mysql
    helm:
      values: | 
        auth:
          database: zenml
          username: zenml
          password: zenml
          rootPassword: password
        primary:
          livenessProbe:
              enabled: true
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 45
              successThreshold: 1
          readinessProbe:
              enabled: true
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 45
              successThreshold: 1
          startupProbe:
              enabled: true
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 45
              successThreshold: 1
          configuration: |-
            [mysqld]
              authentication_policy='* ,,'
              skip-name-resolve
              explicit_defaults_for_timestamp
              basedir=/opt/bitnami/mysql
              plugin_dir=/opt/bitnami/mysql/lib/plugin
              port=3306
              mysqlx=0
              mysqlx_port=33060
              socket=/opt/bitnami/mysql/tmp/mysql.sock
              datadir=/bitnami/mysql/data
              tmpdir=/opt/bitnami/mysql/tmp
              max_allowed_packet=16M
              bind-address=*
              pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
              log-error=/opt/bitnami/mysql/logs/mysqld.log
              character-set-server=UTF8
              collation-server=utf8mb4_0900_ai_ci
              slow_query_log=0
              long_query_time=10.0

              [client]
              port=3306
              socket=/opt/bitnami/mysql/tmp/mysql.sock
              default-character-set=UTF8
              plugin_dir=/opt/bitnami/mysql/lib/plugin

              [manager]
              port=3306
              socket=/opt/bitnami/mysql/tmp/mysql.sock

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
