apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-zenml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 13.0.0
    chart: mysql
    helm:
      values: | 
        auth:
          database: zenml
          username: zenml
          password: zenml
        primary:
          livenessProbe:
              enabled: true
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 45
              successThreshold: 1
          readinessProbe:
              enabled: true
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 45
              successThreshold: 1
          startupProbe:
              enabled: true
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 45
              successThreshold: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
