apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://helm.neo4j.com/neo4j
    targetRevision: 5.26.0
    chart: neo4j
    helm:
      values: |
        neo4j:
          name: neo4j
          password: password
        service:
          neo4j:
            spec:
              type: ClusterIP
        env:
          NEO4J_PLUGINS: '["apoc"]'
        config:
          server.directories.plugins: "/var/lib/neo4j/labs"
          dbms.security.procedures.unrestricted: "apoc.*"
          server.config.strict_validation.enabled: "false"
          dbms.security.procedures.allowlist: "apoc.*"
        volumes:
          data:
            mode: defaultStorageClass
            defaultStorageClass:
              requests:
                storage: 2Gi
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j-reverse-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://helm.neo4j.com/neo4j
    targetRevision: 5.26.0
    chart: neo4j-reverse-proxy
    helm:
      values: |
        reverseProxy:
          serviceName: neo4j-admin
          ingress:
            enabled: true
            host: neo4j.tgu.ovh
            annotations: 
              cert-manager.io/cluster-issuer: "letsencrypt-prod" 
            tls: 
              enabled: true
              config: 
                - secretName: neo4j-tls
                  hosts:
                    - neo4j.tgu.ovh
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
