apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 5.24.2
    chart: bitnami/neo4j
    helm:
      values: |
        neo4j:
          name: neo4j
          password: "password"
        ingress:
          enabled: true
          hostname: neo4j.tgu.ovh
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://neo4j.tgu.ovh"
          pathType: ImplementationSpecific
          hosts:
            - host: neo4j.tgu.ovh
              paths:
                - /
          tls: true
          secret: neo4j-tls
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
