apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: netdata
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://netdata.github.io/helmchart/
    targetRevision: 3.7.144
    chart: netdata
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/ingress.class: public
            kubernetes.io/tls-acme: "true"
          path: /
          pathType: Prefix
          hosts:
          - netdata.tgu.ovh
          ## whole spec is going to be included into ingress spec.
          ## if you intend to use ingressClassName declaration, remove ingress.class from annotations
          spec:
            ingressClassName: public
          tls:
            - secretName: netdata-tls
              hosts:
                - netdata.tgu.ovh
        configs:
          netdata:
            enabled: true
            path: /etc/netdata/netdata.conf
            data: |
              [global]
                hostname = {{ .Values.parent.hostname }}
              [db]
                mode = dbengine

              [plugins]
                cgroups = no
                tc = no
                enable running new plugins = no
                check for new plugins every = 72000
                python.d = no
                charts.d = no
                go.d = no
                node.d = no
                apps = no
                proc = no
                idlejitter = no
                diskspace = no
              [web]
                # Allow only localhost connections
                allow connections from = localhost

                # Allow only from management LAN running on `10.X.X.X`
                allow connections from = 192.168.88.*

                # Allow connections only from a specific FQDN/hostname
                allow connections from = *.tgu.ovh
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
