apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: netdata
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://netdata.github.io/helmchart/
    targetRevision: 3.7.144
    chart: netdata
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - netdata.tgu.ovh
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            - hosts:
                - netdata.tgu.ovh
              secretName: netdata-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
