apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.10.0
    chart: csi-driver-nfs
    helm: 
      values: | 
        kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
