apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-operator
  namespace: argocd
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://zufardhiyaulhaq.com/ngrok-operator/charts/releases/"
    targetRevision: 1.1.0
    chart: ngrok-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
