apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: main
    path: kubeflow/kubeflow/notebooks/notebook-controller
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
