apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onyxia
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://inseefrlab.github.io/helm-charts"
    targetRevision: 3.7.0
    chart: onyxia
    helm:
      values: |
        serviceAccount:
          clusterAdmin: true
        ingress:
          enabled: true
          hosts:
            - host: onyxia.tgu.ovh
        ui:
          image:
            # Update on your own therm but update!
            # https://hub.docker.com/r/inseefrlab/onyxia-api/tags
            version: 2.1.10
          env:
            KEYCLOAK_REALM: datalab
            KEYCLOAK_URL: https://auth.lab.tgu.ovh/auth
        api:
          image:
            # Same here
            # https://hub.docker.com/r/inseefrlab/onyxia-api/tags
            version: latest
          env:
            security.cors.allowed_origins: "http://localhost:3000"
            authentication.mode: openidconnect
            keycloak.realm: datalab
            keycloak.auth-server-url: https://keycloak-http.datalab.svc.cluster.local/auth
          regions:
            [
              {
                  "id":"demo",
                  "name":"Demo",
                  "description":"This is a demo region, feel free to try Onyxia !",
                  "services":{
                    "type":"KUBERNETES",
                    "singleNamespace":false,
                    "namespacePrefix":"user-",
                    "usernamePrefix":"oidc-",
                    "groupNamespacePrefix":"projet-",
                    "groupPrefix":"oidc-",
                    "authenticationMode":"admin",
                    "expose":{
                        "domain":"lab.tgu.ovh"
                    },
                    "monitoring":{
                        "URLPattern":"todo"
                    },
                    "cloudshell":{
                        "catalogId":"inseefrlab-helm-charts-datascience",
                        "packageName":"cloudshell"
                    },
                    "initScript":"https://inseefrlab.github.io/onyxia/onyxia-init.sh"
                  },
                  "data":{
                    "S3":{
                        "URL":"todo",
                        "monitoring":{
                          "URLPattern":"todo"
                        }
                    }
                  },
                  "auth":{
                    "type":"openidconnect"
                  },
                  "location":{
                    "lat":48.8164,
                    "long":2.3174,
                    "name":"Montrouge (France)"
                  }
              }
            ]
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
