apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata-dependencies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openmetadata
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.open-metadata.org/
    targetRevision: 1.9.11
    chart: openmetadata-dependencies
    helm:
      values: |
        mysql:
          enabled: false
        airflow:
          flower:
            enabled: false
          redis:
            enabled: false
            image:
              repository: bitnamilegacy/redis
          postgresql:
            enabled: true
          pgbouncer:
            enabled: false
          externalDatabase:
            host: ""
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openmetadata
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.open-metadata.org/
    targetRevision: 1.9.10
    chart: openmetadata
    helm:
      values: |
        openmetadata:
          config:
            database:
              enabled: true
              driverClass: org.postgresql.Driver
              host: postgresql-openmetadata.openmetadata.svc.cluster.local
              port: 5432
              dbScheme: postgres
              databaseName: openmetadata
              auth:
                username: openmetadata
                password: 
                  secretRef: postgres-secrets
                  secretKey: password
        ingress:
          enabled: true
          className: ""
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: openmetadata.tgu.ovh
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: 
            - secretName: tls-open-metadata
              hosts:
                - openmetadata.tgu.ovh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
