apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata-dependencies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openmetadata
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://helm.open-metadata.org/
    targetRevision: 1.9.10
    chart: openmetadata-dependencies
    helm:
      values: |
        mysql:
          readinessProbe:
            enabled: true
            initialDelaySeconds: 800
            periodSeconds: 80
            timeoutSeconds: 120
            failureThreshold: 10
          livenessProbe:
            enabled: true
            initialDelaySeconds: 800
            periodSeconds: 80
            timeoutSeconds: 120
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            enabled: true
            initialDelaySeconds: 800
            periodSeconds: 80
            timeoutSeconds: 120
            failureThreshold: 10
            successThreshold: 1
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---