apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plausible
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cv
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://imio.github.io/helm-charts
    chart: plausible-analytics
    targetRevision: 0.3.3
    helm:
      values: |
        baseURL: https://plausible.tgu.ovh
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://plausible.tgu.ovh"
          hosts:
            - plausible.tgu.ovh
          tls:
           - secretName: chart-example-tls
             hosts:
               - plausible.tgu.ovh


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true