apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pomerium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: pomerium/
    repoURL: https://github.com/tom333/my-kluster.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
