apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-hive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 12.8.1
    chart: postgresql
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: hive
              password: password
              database: metastore
          primary:
            pgHbaConfiguration: |-
              password_encryption = md5

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
