apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-openmetadata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openmetadata
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.0.8
    chart: postgresql
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: openmetadata
              password: openmetadata
              database: openmetadata
        primary:
          initdb:
            scripts:
              init_openmetadata_db_scripts.sql: |
                CREATE DATABASE openmetadata_db;
                CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
                GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
                commit;
              init_airflow_db_scripts.sql: |
                CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
                GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
                commit;
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
