apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 16.5.5
    chart: postgresql
    helm:
      parameters:
        - name: global.postgresql.auth.username
          value: "data"
        - name: global.postgresql.auth.password
          value: "password"
        - name: global.postgresql.auth.database
          value: "data"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
