apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-guacamole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guacamole
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 12.1.14
    chart: postgresql
    helm:
      parameters:
        - name: global.postgresql.auth.username
          value: "guacamole"
        - name: global.postgresql.auth.password
          value: "guacamole"
        - name: global.postgresql.auth.database
          value: "guacamole"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
