apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-yatai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: yatai
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.7.19
    chart: postgresql
    helm:
      parameters:
        - name: global.postgresql.auth.username
          value: "yatai"
        - name: global.postgresql.auth.password
          value: "yatai"
        - name: global.postgresql.auth.database
          value: "yatai"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
