apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://prefecthq.github.io/prefect-helm"
    targetRevision: 2023.02.23
    chart: prefect-server
    helm:
      values: |
        server:
          publicApiUrl: prefect.tgu.ovh

        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingress.pomerium.io/allowed_users: |
              - laboitatom@gmail.com
            ingress.pomerium.io/allow_any_authenticated_user: 'true'
            ingress.pomerium.io/allow_websockets: 'true'
          className: "pomerium"
          host:
            hostname: prefect.tgu.ovh
            tls:
              enabled: true
              secretName: airflow-web-tls
          tls:
            enabled: true
            secretName: airflow-web-tls
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
