apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.1.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - grafana.tgu.ovh
            tls:
              - secretName: grafana-general-tls
                hosts:
                  - grafana.tgu.ovh
        

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
  
