apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://getredash.github.io/contrib-helm-chart/
    targetRevision: 3.1.0-alpha9
    chart: redash
    helm:
      values: |
        ingress:
          enabled: true
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          pathType: ImplementationSpecific
          hosts:
            - host: redash.tgu.ovh
              paths:
                - /
          tls:
            - secretName: redash-tls
              hosts:
                - redash.tgu.ovh
        redash:
          cookieSecret: 0KlZAHnr6R1jSazwZfKLyz5V116g2RBNI0NR3y7liUA=
          secretKey: Dmgq7ojSBHa6CSkdEXzviRD/M7vYS6uTAVj3FockS1g=
        postgresql:
          auth:
            password: fwObyh6iDnpN9fxFTb4Uj5dlYc7HXDKlrJvFkFeRfr4=
        redis:
          enabled: false
          auth:
            password: DVDqmITJ6JG1hiB97PkKa9XNXUziqho3xGNiPZ6R8pA=

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
