apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: infra
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://helm.twun.io"
    targetRevision: 2.1.0
    chart: docker-registry
    helm:
      parameters:
        - name: persistence.enabled
          value: "true"
        - name: namespace
          value: "infra"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts
          value: ["registry.home.lan"]

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
