apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ""
    repoURL: "https://bitnami-labs.github.io/sealed-secrets/"
    targetRevision: 2.7.0
    chart: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
