apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhost
    server: https://kubernetes.default.svc
  project: selfhost-project
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: ghcr.io/seerr-team/seerr
                  tag: latest
                env:
                  TZ: "Europe/Paris"
        service:
          main:
            controller: main
            ports:
              http:
                port: 5055
        ingress:
          main:
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://seerr.tgu.ovh"
            hosts:
              - host: seerr.tgu.ovh
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http
            tls:
              - secretName: seerr-tls
                hosts:
                  - seerr.tgu.ovh
        persistence:
          config:
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 2Gi
            globalMounts:
              - path: /app/config
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
