apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skooner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    source:
    path: kubernetes-skooner.yaml
    repoURL: https://github.com/skooner-k8s/skooner.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true












    repoURL: https://raw.githubusercontent.com/skooner-k8s/skooner/master/kubernetes-skooner.yaml
    targetRevision: 0.0.6
    chart: skooner
    helm:
      values: | 
        ingress:
          enabled: true
          annotations:  
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://skooner.tgu.ovh"
          hosts:
            - host: skooner.tgu.ovh
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: skooner-tls
              hosts:
                - skooner.tgu.ovh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true