apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selfhost
    server: https://kubernetes.default.svc
  project: selfhost-project
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: lscr.io/linuxserver/sonarr
                  tag: latest
                env:
                  TZ: "Europe/Paris"
                  PUID: "1000"
                  PGID: "1000"
        service:
          main:
            controller: main
            ports:
              http:
                port: 8989
        ingress:
          main:
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://sonarr.tgu.ovh"
            hosts:
              - host: sonarr.tgu.ovh
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http
            tls:
              - secretName: sonarr-tls
                hosts:
                  - sonarr.tgu.ovh
        persistence:
          config:
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 2Gi
            globalMounts:
              - path: /config
          torrents:
            # Même hostPath que qBittorrent pour accéder aux fichiers téléchargés
            type: hostPath
            hostPath: /opt/media-stack/torrents
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /data/torrents
          media:
            # NAS NFS — destination finale des séries
            type: persistentVolumeClaim
            existingClaim: media-nas-pvc
            globalMounts:
              - path: /media
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
