apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  namespace: argocd
spec:
  destination:
    namespace: spark
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '5.7.14'
    chart: bitnami/spark
    helm:
      parameters:
        - name: ingress.hostname
          value: spark.home.lan
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true