apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ''
    repoURL: 'https://apache.github.io/superset'
    targetRevision: 0.5.3
    chart: superset
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts
          value: superset.home.lan
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true