apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: ''
    repoURL: 'https://apache.github.io/superset'
    targetRevision: 0.5.3
    chart: superset
    helm:
      values: |
        ingress:
          enabled: true
          # ingressClassName: nginx
          annotations: {}
            # kubernetes.io/tls-acme: "true"
            ## Extend timeout to allow long running queries.
            # nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
            # nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
            # nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
          path: /
          pathType: ImplementationSpecific
          hosts:
            - superset.home.lan
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true