apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://apache.github.io/superset"
    targetRevision: 0.15.0
    chart: superset
    helm:
      values: |
        bootstrapScript: |
          #!/bin/bash
          uv pip install ".[postgres]" ".[duckdb]" &&\
          if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
        ingress:
          enabled: true
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          path: /
          pathType: ImplementationSpecific
          hosts:
            - superset.tgu.ovh
          tls:
            - secretName: superset-tls
              hosts:
                - superset.tgu.ovh
        configOverrides:
          my_override: |
            PUBLIC_ROLE_LIKE = "Gamma"
            FEATURE_FLAGS = {
                "DASHBOARD_RBAC": True
            }
          secret: |
            SECRET_KEY = 'JojBoOGWGAT7al1LDHtvvwRPxcrH62cinea62nO7ZXPPcLYAoOiTaPOW'
        postgresql:
          postgresqlPassword: superset
        supersetNode:
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
            periodSeconds: 10
            successThreshold: 1
        syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
