apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teleport
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    repoURL: https://charts.releases.teleport.dev
    targetRevision: 18.2.0
    chart: teleport-cluster
    helm:
      values: |
        chartMode: standalone
        clusterName: teleport.tgu.ovh
        proxyListenerMode: multiplex
        acme: true
        acmeEmail: laboitatom@gmail.com
        publicAddr: ['teleport.tgu.ovh:443']
        highAvailability:
          certManager:
            enabled: true
            addPublicAddrs: true
            addCommonName: true
            issuerName: letsencrypt-prod-dns
            issuerKind: ClusterIssuer
          replicaCount: 1
        service:
          type: ClusterIP
        proxy:
          service:
            type: ClusterIP
            annotations: {}
          ingress:
            enabled: true
            className: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-dns
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            hosts:
              - host: teleport.tgu.ovh
                paths:
                  - path: /
                    pathType: ImplementationSpecific      
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
