apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-forward-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: traefik-forward-auth
  source:
    path: ""
    repoURL: "https://k8s-at-home.com/charts/"
    targetRevision: 2.2.2
    chart: traefik-forward-auth

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
