apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tt-rss
  namespace: argocd
spec:
  destination:
    namespace: tt-rss
    server: https://kubernetes.default.svc
  project: tt-rss-project
  source:
    path: ''
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: '4.2.0'
    chart: tt-rss
    helm:
      parameters:
        - name: ingress.main.enabled
          value: 'true'
        - name: postgresql.persistence.enabled
          value: 'true'
      valueFiles:
        - https://raw.githubusercontent.com/tom333/my_kluster/main/argocd/argocd-apps/tt-rss-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true