apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tt-rss
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tt-rss
    server: https://kubernetes.default.svc
  project: tt-rss-project
  source:
    repoURL: "https://angelnu.github.io/helm-charts"
    targetRevision: "6.0.0"
    chart: tt-rss
    helm:
      values: |
        env: 
          TTRSS_SELF_URL_PATH: https://rss.tgu.ovh
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/auth-url: "https://auth.tgu.ovh/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://auth.tgu.ovh/oauth2/start?rd=https://rss.tgu.ovh"
            hosts:
              - host: rss.tgu.ovh
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      port: 8080
            tls:
              - hosts:
                  - rss.tgu.ovh
        postgresql:
          persistence:
            enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
