apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yatai
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://bentoml.github.io/helm-charts"
    targetRevision: 1.1.2
    chart: yatai
    helm:
      valueFiles:
        - values.yaml
      valuesLiteral:
        - name: values.yaml
          value: |
            postgres.host: "postgresql-yatai.datalab.svc.cluster.local"
            postgresql.port: 5432
            postgresql.database: "yatai"
            postgresql.user: "yatai"
            postgresql.password: "password"
            artifactRoot.s3.enabled: true
            artifactRoot.s3.bucket: yatai
            artifactRoot.s3.awsAccessKeyId: mlflow
            artifactRoot.s3.awsSecretAccessKey: "Passw0rd"
            extraEnvVars.MLFLOW_S3_ENDPOINT_URL: "http://minio.datalab.svc.cluster.local:9000"
            ingress:
              enabled: true
              hosts:
              - host: yatai.tgu.ovh
                paths:
                - /

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
