apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yatai
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: ""
    repoURL: "https://bentoml.github.io/helm-charts"
    targetRevision: 1.1.4
    chart: yatai
    helm:
      values: |
        postgresql:
          host: postgresql-yatai.datalab.svc.cluster.local
          port: 5432
          database: yatai
          user: yatai
          password: password
        s3:
          endpoint: http://minio.datalab.svc.cluster.local:9000
          bucketName: yatai
          accessKey: mlflow
          secretKey: Passw0rd

        ingress:
          enabled: true
          hosts:
          - host: yatai.tgu.ovh
            paths:
            - /

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
