apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenml
  namespace: argocd
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: "https://github.com/zenml-io/zenml"
    path: src/zenml/zen_server/deploy/helm/
    targetRevision:  0.34.0
    helm:
      values: |
        zenml:
        authType: NO_AUTH
        defaultPassword: password
        ingress:
          enabled: true
          className: pomerium
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingress.pomerium.io/allowed_users: |
              - laboitatom@gmail.com
            ingress.pomerium.io/allow_any_authenticated_user: 'true'
            ingress.pomerium.io/allow_websockets: 'true'
          tls:
            enabled: true
            generateCerts: false
          host: zenml.tgu.ovh

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
