apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: helm/
    repoURL: https://github.com/tom333/zenml.git
    chart: zenml
    targetRevision: 17e45a2366025e4023c458e9de7357ab1176faf5
    helm:
      values: |
        zenml:
          database:
            url: "mysql://zenml:zenml@mariadb.datalab.svc.cluster.local:3306/zenml"
          ingress:
            enabled: true
            annotations: 
              cert-manager.io/cluster-issuer: letsencrypt-prod        
            host: zenml.tgu.ovh
            tls:
              enabled: true
          deploymentType: local
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 150
            periodSeconds: 150
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
