apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: public.ecr.aws/zenml
    chart: zenml
    targetRevision: 0.83.0
    helm:
      values: |
        zenml:
          database:
            url: "mysql://zenml:zenml@mariadb.datalab.svc.cluster.local:3306/zenml"
          auth:
            authType: NO_AUTH
          ingress:
            enabled: true
            annotations: 
              cert-manager.io/cluster-issuer: letsencrypt-prod        
            host: zenml.tgu.ovh
            tls:
              enabled: true
          deploymentType: local

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
