apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datalab
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    repoURL: https://charts.zitadel.com
    chart: zitadel
    targetRevision: 8.13.4
    helm:
      values: |
        zitadel:
          masterkey: x123456789012345678901234567891y
          configmapConfig:
            ExternalSecure: false
            ExternalDomain: zitadel.tgu.ovh
            TLS:
              Enabled: true
            Database:
              Postgres:
                Host: postgresql-zitadel.datalab.svc.cluster.local
                Port: 5432
                Database: zitadel
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: 30m
                MaxConnIdleTime: 5m
                User:
                  Username: zitadel
                  Password: zitadel
                  SSL:
                    Mode: disable
                Admin:
                  Username: zitadel
                  Password: zitadel
                  SSL:
                    Mode: disable
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: zitadel.tgu.ovh
              paths:
              - path: /
                pathType: ImplementationSpecific
          tls: 
            - secretName: zitadel-tls
              hosts:
                - zitadel.tgu.ovh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
