apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: laboitatom@email.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-cert
  namespace: istio-system
spec:
  dnsNames:
    - kubeflow.tgu.ovh
  secretName: kubeflow-tls-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
