apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akeyless-secret-store
  namespace: datalab
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://api.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-secret-creds
            key: accessId
          accessType:
            name: akeyless-secret-creds
            key: accessType
          accessTypeParam:
            name: akeyless-secret-creds
            key: accessTypeParam
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: datalab
spec:
  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: keycloak-hub-secret
    creationPolicy: Owner

  data:
    - secretKey: keycloak-hub-secret
      remoteRef:
        key: /keycloak/keycloakadminsecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: datalab
spec:
  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: minio-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: /minio/miniorootuser
