apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akeyless-secret-store
  namespace: jupyter
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://api.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-secret-creds
            key: accessId
          accessType:
            name: akeyless-secret-creds
            key: accessType
          accessTypeParam:
            name: akeyless-secret-creds
            key: accessTypeParam
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jupyter-secret
  namespace: jupyter
spec:
  refreshInterval: 24h

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: jupyter-hub-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: /jupyter/jupyterhubsecret
