apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
spec:
  rules:
    - host: argocd.tgu.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
