apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-kubeflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
    - host: kubeflow.tgu.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-argocd-ingress
  namespace: argocd

spec:
  ingressClassName: public
  rules:
    - host: argocd.tgu.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
