apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd-public-ingress
spec:
  rules:
    - host: argocd.tgu.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: datalab
#   name: trino-public-ingress
# spec:
#   rules:
#     - host: trino.tgu.ovh
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: trino
#                 port:
#                   number: 8080
# ---

