apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: kubeflow
  name: kubeflow-ingress
  namespace: kubeflow
  #annotations:
  #kubernetes.io/ingress.class: "traefik"
  #cert-manager.io/issuer: "kubeflow-selfsigned-issuer"
spec:
  rules:
    - host: kubeflow.home.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
  # tls:
  #   - hosts:
  #       - ingress-demo.example.com
  #     secretName: kubeflow.home.lan
