apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: kubeflow
  name: kubeflow-ingress
  namespace: kubeflow
spec:
  rules:
    - host: kubeflow.home.lan
      http:
        paths:
          - path: /
            backend:
              serviceName: kistio-ingressgateway
              servicePort: 8080

