# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   labels:
#     app: kubeflow
#   name: kubeflow-ingress
#   namespace: kubeflow
#annotations:
#kubernetes.io/ingress.class: "traefik"
#cert-manager.io/issuer: "kubeflow-selfsigned-issuer"
# spec:
#   rules:
#     - host: kubeflow.home.lan
#       http:
#         paths:
#           - path: /*
#             pathType: Prefix
#             backend:
#               service:
#                 name: istio-ingressgateway
#                 port:
#                   number: 80
# tls:
#   - hosts:
#       - ingress-demo.example.com
#     secretName: kubeflow.home.lan
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow.home.lan
  namespace: istio-system
spec:
  dnsNames:
    - kubeflow.home.lan
  secretName: kubeflow.home.lan
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: istio-ingressgateway-web
  namespace: istio-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kubeflow.home.lan`) && PathPrefix(`/`)
      services:
        - name: istio-ingressgateway
          port: 80
  tls:
  certResolver: selfsigned
