---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow.home.lan
  namespace: kubeflow
spec:
  dnsNames:
    - kubeflow.home.lan
  secretName: kubeflow.home.lan
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: istio-ingressgateway-web-tls
  namespace: kubeflow
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kubeflow.home.lan`) && PathPrefix(`/`)
      services:
        - name: istio-ingressgateway
          port: 30721
  tls:
    certResolver: kubeflow.home.lan
