---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingress
  namespace: kubeflow
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio.home.lan`) && PathPrefix(`/`)
      services:
        - name: minio-service
          port: 9000
