---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.home.lan
  namespace: kube-system
spec:
  dnsNames:
    - traefik.home.lan
  secretName: traefik.home.lan
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.home.lan`) && PathPrefix(`/`)
      services:
        - name: api@internal
          kind: TraefikService
