- hosts: server
  become: yes
  become_method: sudo
  vars:
    k3s_release_version: v1.21.8+k3s2
    k3s_become: yes
    # k3s_server:
    #      disable:
    #        - traefik
    #        - servicelb
  roles:
     - role: xanmanning.k3s


