- hosts: server
  become: yes
  become_method: sudo
  vars:
    k3s_release_version: v1.21.8+k3s2
    k3s_become: yes
    microk8s_version: "1.21/stable"
  roles:
     - role: istvano.microk8s
       vars:
         microk8s_plugins:
           dns: "1.1.1.1"
           istio: true
           ingress: true
           gpu: true
           kubeflow: kubeflow-lite
