---
- name: Restart wyoming-satellite
  become: true
  become_user: "{{ wyoming_satellite_user }}"
  ansible.builtin.systemd:
    name: wyoming-satellite.service
    scope: user
    daemon_reload: true
    state: restarted
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ wyoming_satellite_uid | default(1000) }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ wyoming_satellite_uid | default(1000) }}/bus"
