argo-cd:
  namespace: argocd
  installCRDs: true
  dex:
    enabled: false
  # repoServer:
  #   volumes:
  #     - name: custom-tools
  #       emptyDir: {}
  #   initContainers:
  #     - name: download-tools
  #       image: alpine:3.16
  #       command: [sh, -c]
  #       args:
  #         - wget https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64 &&
  #           mv kustomize_3.2.0_linux_amd64 /custom-tools/kustomize_3.2.0 &&
  #           chmod +x /custom-tools/kustomize_3.2.0
  #       volumeMounts:
  #         - mountPath: /custom-tools
  #           name: custom-tools
  #   volumeMounts:
  #     - mountPath: /usr/local/bin/kustomize_3.2.0
  #       name: custom-tools
  #       subPath: kustomize_3.2.0
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      hosts:
        - argocd.tgu.ovh
    # certificate:
    #   enabled: true
    #   domain: argocd.home.lan
    #   issuer:
    #     kind: # ClusterIssuer
    #     name: selfsigned-issuer
    #   additionalHosts: []
    #   secretName: argocd-server-tls

    config:
      # kustomize.path.v3.2.0: /usr/local/bin/kustomize_3.2.0
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          name: repo-perso
          url: https://github.com/tom333/my-kluster.git
        - type: helm
          name: bitnami-labs
          url: https://bitnami-labs.github.io/sealed-secrets/
        - type: helm
          name: v3io-stable
          url: https://v3io.github.io/helm-charts/stable
