argo-cd:
  installCRDs: true
  dex:
    enabled: false
  redis-ha:
    enabled: false
    
  controller:
    replicas: 1
  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2
  server:
    replicas: 2
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: true
      extraTls:
      - hosts:
        - argocd.tgu.ovh
        secretName: argocd-tls
  certificate:
    enabled: true
  global:
    domain: argocd.tgu.ovh

