argo-cd:
  installCRDs: true
  dex:
    enabled: false
  redis-ha:
    enabled: false
    
  controller:
    replicas: 1
  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1
  server:
    replicas: 1
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      extraTls:
        - hosts:
          - argocd.tgu.ovh
          secretName: argocd-tls
    env: 
      - name: ARGOCD_EXEC_TIMEOUT
        value: 10m
  certificate:
    enabled: true
  global:
    domain: argocd.tgu.ovh

