applications:
  - name: argocd
    namespace: argocd
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
          - https://raw.githubusercontent.com/tom333/my-kluster/main/argocd/argocd-install/values.yaml
      path: argocd/argocd-install
      repoURL: https://github.com/tom333/my-kluster.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
  - name: applications
    namespace: argocd
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd/argocd-apps
      repoURL: https://github.com/tom333/my-kluster.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  - name: projects
    namespace: argocd
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd/argocd-appprojects
      repoURL: https://github.com/tom333/my-kluster.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
projects:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
