applications:
  argocd:
    namespace: default
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
          - https://raw.githubusercontent.com/tom333/my-kluster/main/argocd/argocd-install/values.yaml
      path: argocd/argocd-install
      repoURL: https://github.com/tom333/my-kluster.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
  applications:
    namespace: default
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd/argocd-apps
      repoURL: https://github.com/tom333/my-kluster.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  projects:
    namespace: default
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd/argocd-appprojects
      repoURL: https://github.com/tom333/my-kluster.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
projects:
  argocd:
    namespace: default
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: default
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
