apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: code-server-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: code-server
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
