apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datalab-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: datalab
      server: https://kubernetes.default.svc
    - namespace: "istio-system"
      server: https://kubernetes.default.svc
    - namespace: "cert-manager"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
