apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jupyter-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: jupyter
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'