apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalab.fullname" . }}-metaflow-ui
  labels:
    {{- include "datalab.labels" . | nindent 4 }}
    app.kubernetes.io/component: metaflow-ui
spec:
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "datalab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metaflow-ui
