apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datalab.fullname" . }}-metaflow-ui
  labels:
    {{- include "datalab.labels" . | nindent 4 }}
    app.kubernetes.io/component: metaflow-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "datalab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metaflow-ui
  template:
    metadata:
      labels:
        {{- include "datalab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: metaflow-ui
    spec:
      containers:
      - name: metaflow-ui
        image: {{ .Values.metaflow.ui.image.repository }}:{{ .Values.metaflow.ui.image.tag | default "latest" }}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: METAFLOW_SERVICE_URL
          value: {{ .Values.metaflow.ui.serviceUrl | quote }}
        - name: METAFLOW_DATASTORE_SYSROOT_S3
          value: {{ .Values.metaflow.s3.bucket | quote }}
        - name: METAFLOW_DEFAULT_DATASTORE
          value: "s3"
        - name: METAFLOW_DEFAULT_METADATA
          value: "service"
        - name: METAFLOW_SERVICE_INTERNAL_URL
          value: {{ .Values.metaflow.ui.internalServiceUrl | quote }}
        resources:
          {{- toYaml .Values.metaflow.ui.resources | nindent 10 }}
