apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalab.fullname" . }}-metaflow-metadata
  labels:
    {{- include "datalab.labels" . | nindent 4 }}
    app.kubernetes.io/component: metaflow-metadata
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "datalab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metaflow-metadata
