apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./common/kubeflow-namespace/base
  - ./common/kubeflow-roles/base
  - ./common/kubeflow-istio-resources/base
  #- ./apps/kfserving/upstream/overlays/kubeflow
  - ./apps/centraldashboard/upstream/overlays/istio
  - ./apps/admission-webhook/upstream/overlays/cert-manager
  - ./apps/profiles/upstream/overlays/kubeflow
  # - ./apps/volumes-web-app/upstream/overlays/istio
  # - ./apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
  # - ./apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
  # - ./apps/training-operator/upstream/overlays/kubeflow
  # - ./apps/mpi-job/upstream/overlays/kubeflow
  - ./common/user-namespace/base
