apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./common/cert-manager/cert-manager/base
  - ./common/cert-manager/kubeflow-issuer/base
  - ./common/istio-1-9/istio-crds/base
  - ./common/istio-1-9/istio-namespace/base
  - ./common/istio-1-9/istio-install/base
  - ./common/dex/overlays/istio
  - ./common/oidc-authservice/base
  - ./common/knative/knative-serving/base
  - ./common/istio-1-9/cluster-local-gateway/base
  - ./common/kubeflow-namespace/base
  - ./common/kubeflow-roles/base
  - ./common/istio-1-9/kubeflow-istio-resources/base
  - ./apps/pipeline/upstream/env/platform-agnostic-multi-user
