apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./mysql.yaml
  - patches/katib-externaldb.yaml

configMapGenerator:
  - envs:
      - pipeline-mysql.env
    name: pipeline-install-config
    namespace: kubeflow
    behavior: merge
secretGenerator:
  - name: katib-mysql-secrets
    behavior: merge
    envs:
      - secrets-envs/katib-mysql.env
  - name: mysql-secret
    behavior: replace
    envs:
      - secrets-envs/pipelines-mysql.env
