FROM codercom:coder:latest

RUN sudo apt update -y && sudo apt install -y python python3-distutils python3-pip python3-virtualenv make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN curl https://pyenv.run | bash
