apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "kubeflow"
spec:
  mtls:
    mode: DISABLE
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kubeflow
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server
  namespace: kubeflow
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  secretName: webhook-server-tls
  commonName: webhook-server.kubeflow.svc
  dnsNames:
    - webhook-server.kubeflow.svc
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
